/* Generated by tools/gen-kitty-ini-template.py from
 * docs/examples/kitty.ini.example - do not edit by hand. This is the
 * kitty.ini KiTTY writes when it starts and finds none.
 *
 * The version on the first line is filled in by the compiler from
 * BUILD_VERSION/BUILD_TIME, not by the generator, so this header must be
 * included where both are defined - kitty.c defines fallbacks for them
 * well above its include. Deliberately NO fallback of its own: a TU that
 * lacks them should fail to compile rather than quietly ship every user a
 * kitty.ini stamped "0.0 @ Undefined", which is the one thing this line
 * exists to prevent. */
char default_init_file_content[] =
"; kitty.ini - written by KiTTY " BUILD_VERSION " @ " BUILD_TIME ".\n"
";\n\
; This is KiTTY's settings file. KiTTY created it because there was none;\n\
; it is yours to edit.\n\
;\n\
; Every supported option is listed below, commented out, led by a description.\n\
; Nothing here is in force: uncomment a line to use it. The values shown are\n\
; the built-in defaults, so uncommenting a line unchanged does nothing today -\n\
; but it does pin that value, where a commented line keeps following the\n\
; default if a later KiTTY changes it.\n\
;\n\
; Some settings are also held in the registry, and outside portable mode the\n\
; registry is read first - so if an edit here seems to have no effect, that is\n\
; usually why. See\n\
;   https://github.com/hknet/KiTTY/blob/kitty-0.84/docs/KITTY-INI.md\n\
\n\
[ConfigBox]\n\
\n\
; dblclick: what a double-click on a saved session does\n\
;    - open: load it and open it in this window (like the Open button)\n\
;    - start: launch it in a new window and keep the configuration box open (like the Start button)\n\
;dblclick=open\n\
\n\
; defaultsettings: when no, 'Default Settings' is hidden from the saved-session\n\
;    list in the config box. The session itself is always there either way - it\n\
;    is the template every new session starts from - so this only decides\n\
;    whether you can see and click it. Default yes (shown, like stock PuTTY).\n\
;    Note it is also the way into quick connect, where you type a host instead\n\
;    of picking a session: you get there by loading Default Settings once. Hide\n\
;    the row and that route is gone unless you set loadlastsession=no below.\n\
;    https://github.com/hknet/KiTTY/blob/kitty-0.84/FEATURES.md#quick-connect-type-a-host-instead-of-picking-a-session\n\
;defaultsettings=yes\n\
\n\
; categoryexpand: how many levels of the config-box Category tree are expanded\n\
;    on open. Default (unset, or all/full) = fully expanded; a number expands only\n\
;    that deep - 1 = top categories only (stock PuTTY), 2 = one level of subtrees,\n\
;    and so on.\n\
;categoryexpand=all\n\
\n\
; filter: with yes (the default), typing in the Saved Sessions NAME BOX narrows\n\
;    the list below to sessions matching what you typed. no leaves the box as a\n\
;    plain name field and the list always shows everything, like stock PuTTY.\n\
;    Typing directly into the list is Windows' own first-letter jump and is not\n\
;    affected either way.\n\
;    Two keys go with it, from anywhere in the configuration box:\n\
;      Ctrl+F  jump to the Session panel and put the cursor in that name box,\n\
;              with what is already there selected so you can type over it.\n\
;              It searches within the folder currently selected.\n\
;      Ctrl+G  the same, but drops the folder filter back to the root list\n\
;              first - \"search everywhere\", for finding a session when you\n\
;              do not remember which folder it is in.\n\
;    Neither loads, moves or saves anything, and neither is affected by\n\
;    [KiTTY] shortcuts.\n\
;filter=yes\n\
\n\
; height: the number of visible lines in the saved-sessions list (default 16 = stock fit)\n\
;height=16\n\
\n\
; loadlastsession: when yes (default), the configuration box opens pre-filled with\n\
;    the session used last. When no, it opens on 'Default Settings' with the caret\n\
;    already in 'Host Name (or IP address)' - quick connect: type a host, press\n\
;    Enter, and every connection starts from the same known configuration instead\n\
;    of inheriting whatever was used before.\n\
;loadlastsession=yes\n\
\n\
; noexit: if yes, closing a window that ran a connected session starts a fresh\n\
;    instance showing the configuration box, so you land back in the session\n\
;    picker. A window that never connected (e.g. the config box itself was\n\
;    cancelled) exits normally, and nothing respawns during system shutdown.\n\
;noexit=no\n\
\n\
; proxyselection: show the named-proxy chooser in the Session panel.\n\
;   auto (default) = show once any named proxy is defined; yes = always; no = never\n\
;   Where you DEFINE one in the first place depends on this setting: with yes\n\
;   the chooser is always in the Session panel and carries an Edit button next\n\
;   to it. With auto the chooser stays hidden until a definition exists, so the\n\
;   way in is Connection > Proxy > \"Edit named proxies...\". no hides both, and\n\
;   nothing in the GUI can then create or edit a definition.\n\
;proxyselection=auto\n\
\n\
; windowheight: force the configuration window to an explicit height, in pixels\n\
;    (scaled for your display DPI). Default 0 = off, so the window is sized from\n\
;    [ConfigBox] height instead. This is a blunt override - it resizes only the\n\
;    outer window, not the inner controls - so [ConfigBox] height is usually what\n\
;    you want. Set a pixel value, e.g. 800, to force it.\n\
;windowheight=0\n\
\n\
\n\
\n\
[KiTTY]\n\
\n\
; antiidle: string sent to the server periodically to keep the connection alive.\n\
;    Default (unset/empty) = disabled. \\k08 sends a backspace; pick a sequence the\n\
;    remote ignores. How often it is sent is set by antiidledelay below.\n\
;antiidle=\\k08\\\n\
\n\
; antiidledelay: how often that string is sent, in seconds. Default 180.\n\
;    Values below 5 are treated as 5, so a typo cannot turn a keepalive into\n\
;    a flood. (Before this it was not seconds: the number was divided by 10 to\n\
;    count ticks of a 30-second timer, so it meant about three times what it\n\
;    said - 60 gave 180 seconds. Divide a carried-over value by three to keep\n\
;    the interval you had.)\n\
;antiidledelay=60\n\
\n\
; autoreconnect: reconnect a session by itself when the link drops, retrying\n\
;    while the network is away. This is one of the premiere features users\n\
;    start using KiTTY for - a session disconnect is no longer a manual job to\n\
;    reconnect but solved by KiTTY for the user. On by default; see\n\
;    ReconnectDelay for how long it waits between attempts.\n\
;autoreconnect=yes\n\
\n\
; bgimage: enable/disable the background image feature. (The description\n\
;    here used to call it backgroundimage, which is not a key KiTTY reads.)\n\
;bgimage=no\n\
\n\
; bcdelay: delay in MILLISECONDS between each character in every automatic\n\
;    keyboard send (autocommand, login script, user commands, send-text boxes).\n\
;    Default 0 = off. Set a few ms (e.g. 3) for hosts that drop characters\n\
;    when input arrives too fast.\n\
;bcdelay=0\n\
\n\
; commanddelay: delay in SECONDS between two lines of the automatic start\n\
;    command script (Connection/Data/Command setting). 0.05 = 50 ms; minimum\n\
;    enforced 0.005.\n\
;commanddelay=0.05\n\
\n\
; conf: `no` stops KiTTY creating and maintaining its own files - kitty.ini is\n\
;   not auto-created, and neither the kitty.sav backup nor the portable-folder\n\
;   backups are written. Only `no` does anything: `conf=yes` is ignored rather\n\
;   than being a way to switch the behaviour back on. It is not remembered\n\
;   either - drop the line and the next start behaves normally.\n\
;   Yes, an option that says \"write no configuration file\" living IN the\n\
;   configuration file contradicts itself. Noted - and it still does what it\n\
;   advertises: no further writes to those files. If you want no kitty.ini at\n\
;   all, put the value in the registry instead - a string value conf = no\n\
;   under HKCU\\Software\\kapper.net\\KiTTY - and delete kitty.ini. Outside\n\
;   portable mode the registry is read first, so it is honoured from there.\n\
;conf=yes\n\
\n\
; configdir: where the settings directories live - Sessions, SshHostKeys and\n\
;    the rest. Portable mode uses it; by default it is the directory kitty.exe\n\
;    sits in.\n\
;    It does NOT move kitty.ini. This file has to be found before anything in\n\
;    it can be read, so KiTTY is already holding it by the time it learns where\n\
;    configdir points - kitty.ini stays where it was.\n\
;    Removing the setting later does not move anything back either: your\n\
;    sessions, host keys and stored keys stay in that directory and KiTTY stops\n\
;    looking there, so they simply disappear from the list. Before you unset or\n\
;    change it, use \"Export all...\" in the configuration box (Session panel),\n\
;    then change the setting, then \"Import all...\" - that carries everything\n\
;    across instead of stranding it.\n\
;configdir=\n\
\n\
; browsedirectory: base directory for portable/session file browsing; normally auto-detected\n\
;browsedirectory=\n\
\n\
; Folders: the list of session folders, written by KiTTY whenever you add or\n\
;    remove one. It is the live list, not a cache of something else, so an\n\
;    edit here is overwritten the next time the folder set changes. Edit it\n\
;    only to recover a folder that has gone missing from the config box.\n\
;Folders=\n\
\n\
; RootFolderLabel: what the configuration box's folder selector calls the root\n\
;    session list. That list is not \"the sessions in no folder\" - it is ALL\n\
;    of them: picking the root switches the folder filter off, so sessions\n\
;    filed in folders stay listed too. Which is why the built-in label says\n\
;    \"All sessions\". Display only - that\n\
;    folder is always stored as \"Default\", so renaming the label changes no\n\
;    session and no saved setting. Normally set from the config box itself:\n\
;    select the root list, type a new name over its label, press Rename; typing\n\
;    the built-in name back restores it. Like Folders, this is stored in\n\
;    whichever backend your save mode uses - the registry in registry mode,\n\
;    this file in file/dir mode.\n\
;RootFolderLabel=All sessions (root)\n\
\n\
; cryptsalt: which salt variant the LEGACY stored-password scrambling uses\n\
;    (the pre-DPAPI scheme - see the password notes in docs/KITTY-INI.md).\n\
;    It is not a security control: the scheme is obfuscation with a\n\
;    compiled-in key either way. Change it only if you know why, and be\n\
;    aware that passwords already stored were scrambled with the previous\n\
;    setting.\n\
;cryptsalt=1\n\
\n\
; CtHelperPath: the full path to the cthelper.exe binary (Wrapper for Cygwin feature)\n\
;CtHelperPath=\n\
\n\
; ctrltab: allow Ctrl+Tab to switch between open KiTTY windows. This is the\n\
;    master switch only - it does not turn the feature on by itself. Each\n\
;    session also has its own \"Switch KiTTY windows with Ctrl + TAB\" box in\n\
;    Window > Behaviour, which is off until you tick it, and that box is only\n\
;    offered while this is yes. no hides the box and disables the key; the\n\
;    -noctrltab command-line switch does the same for one window.\n\
;ctrltab=yes\n\
\n\
; debug: extra tracing in the Event Log - saved-session lookups, the automatic\n\
;    command, key remappings, the internal editor, and the pscp / WinSCP\n\
;    command lines actually run. The password those command lines carry is\n\
;    blanked in the log, but the host, user, paths and switches are not, so\n\
;    read a debug log before you send it to anyone.\n\
;    It also enables /passwd, which shows this session's password and copies\n\
;    it to the clipboard; without debug mode that command is treated as plain\n\
;    text and sent to the host instead. /debug turns all of this on and off at\n\
;    runtime, so it does not have to live in this file.\n\
;debug=no\n\
\n\
; downloaddir: this is the local directory where files are downloaded with the pscp integration\n\
;downloaddir=\n\
\n\
; uploaddir: default remote directory used by the pscp upload integration\n\
;uploaddir=.\n\
\n\
; fileextension: the extension for session settings files in portable mode\n\
;fileextension=.ktx\n\
\n\
; hyperlink: enable/disable the hyperlink feature\n\
;hyperlink=yes\n\
\n\
; iconfile: point to a file where internal icons are located\n\
;iconfile=kitty.exe\n\
\n\
; initdelay: how long KiTTY waits after the terminal opens before it starts\n\
;    typing for you - the auto-command (including a \\p password step in it).\n\
;    In seconds, fractions allowed: 0.5 is half a second. Default 2.0; a\n\
;    negative value is ignored. It also sets the delay before an\n\
;    autosendtotray session drops itself into the tray.\n\
;initdelay=2.0\n\
\n\
; KiClassName: the Windows window-class name KiTTY registers, which also selects\n\
;    which registry hive it reads/writes sessions in. Default (unset): KiTTY's own\n\
;    class and hive (Software\\kapper.net\\KiTTY). Set to PuTTY to use stock PuTTY's\n\
;    window class AND PuTTY's hive (Software\\SimonTatham\\PuTTY) - handy to share\n\
;    sessions with an installed PuTTY, or for host tools that key off the \"PuTTY\"\n\
;    window class. This is NOT the default; leave it unset for normal use.\n\
;KiClassName=PuTTY\n\
\n\
; modalerrors: show connection errors as modal pop-up boxes instead of inline\n\
;    in the terminal (upstream cyd01/KiTTY #548). Default no - inline, so an\n\
;    error cannot trap the window behind a dialog.\n\
;modalerrors=no\n\
\n\
; modalnewhostkeyconfirmation: how to confirm an UNKNOWN (first-seen) host key.\n\
;    Default yes = classic modal dialog box. no = OpenSSH-style prompt in the\n\
;    terminal; type \"yes\" to accept and cache the key, \"once\" to connect without\n\
;    caching it, anything else cancels.\n\
;modalnewhostkeyconfirmation=yes\n\
\n\
; modalchangedhostkeyconfirmation: how to handle a CHANGED host key (differs from\n\
;    the cached one). Default yes = classic modal dialog box (you can Accept to\n\
;    update the cache). no = in-terminal \"double opt-in\": first type \"yes\" to\n\
;    accept the new key for this connection, then - because KiTTY cannot verify a\n\
;    plain SSH key's authenticity - you are asked separately whether to REPLACE\n\
;    the stored key for future connections, which requires typing the exact word\n\
;    \"confirmed\" (a plain \"yes\" is re-asked, not accepted). Decline the replace\n\
;    and you connect this once with the old key kept (asked again next time).\n\
;modalchangedhostkeyconfirmation=yes\n\
\n\
; modalweakkeyconfirmation: how to confirm a weak crypto algorithm / weak cached\n\
;    host key (below the warning threshold). Default yes = classic modal dialog\n\
;    box. no = OpenSSH-style prompt in the terminal; type \"yes\" to accept.\n\
;    Note: all three of these prompts fall back to an in-terminal error + abort\n\
;    if they occur during an already-authenticated session (a rekey), where no\n\
;    inline prompt is possible.\n\
;modalweakkeyconfirmation=yes\n\
\n\
; mouseshortcuts: the two mouse chords in the terminal window -\n\
;    Ctrl+Shift+left-click duplicates the session, Ctrl+middle-click sends the\n\
;    window to the tray. Default yes.\n\
;    Why turn them off: both chords are swallowed by KiTTY and never reach the\n\
;    host, so a program in the terminal that wants them - anything using\n\
;    xterm-style mouse reporting, and middle-click paste in particular - will\n\
;    look broken. Ctrl+Shift+left-click is also easy to hit by accident while\n\
;    selecting text, and it opens a whole new window when you do. Set no and\n\
;    the mouse behaves as it does in stock PuTTY; the same two actions stay\n\
;    available from the window menu and from their keyboard shortcuts.\n\
;    Protect mode and PuTTY mode switch them off regardless of this setting.\n\
;mouseshortcuts=yes\n\
\n\
; internaldelay: how long KiTTY pauses, in milliseconds, while it types for\n\
;    you - between the lines of a multi-line send, and around each\n\
;    synthesised keystroke that carries Ctrl/Shift/Alt. It paces the login\n\
;    and automatic commands, \\n breaks in the send-text boxes, user-command\n\
;    menu entries and remapped keys. Default 10, minimum 1.\n\
;    Raise it if a host drops characters out of a scripted or pasted block -\n\
;    a slow link or a shell that echoes lazily needs more than 10 ms per\n\
;    line. It has no effect on ordinary typing or on paste.\n\
;internaldelay=10\n\
\n\
; pastesize: warn before a large paste into the terminal. When the clipboard\n\
;    holds more than this many characters, KiTTY names the count and the\n\
;    limit and asks before sending anything - and the default answer is No,\n\
;    so a stray Enter cancels the paste instead of flooding the shell.\n\
;    The default is 5120 characters - about 5 KB, the same threshold Windows\n\
;    Terminal warns at. 0 switches the warning off entirely. It counts\n\
;    characters rather than lines, and judges only the size: what the\n\
;    clipboard actually contains is not examined.\n\
;    Note this key is read from the registry first (outside portable mode), so\n\
;    if a pastesize value ever lands there, changing the line here has no\n\
;    effect until you delete the registry value.\n\
;pastesize=5120\n\
\n\
; proxychainmax: how many chained SSH proxies (jump hosts) a connection may use\n\
;    before it is refused with an error. Stops a proxy chain that loops back on\n\
;    itself from hanging. Default 5; values below 1 are ignored.\n\
;proxychainmax=5\n\
\n\
; namedproxy: how a named proxy's Host field is read when the proxy entry\n\
;    itself does not say:\n\
;      sessionorhostname = the title of a saved session first, then a\n\
;                          hostname (the default - what PuTTY has always\n\
;                          done, and existing configurations may rely on it)\n\
;      hostname          = a hostname, full stop. Guards against a jump host\n\
;                          that happens to share a name with a saved session\n\
;                          silently dragging that session's whole config in.\n\
;    A proxy entry that says for itself overrides this.\n\
;namedproxy=sessionorhostname\n\
\n\
; funkeys: the default function-key mode for sessions that do not carry one,\n\
;    spelled as the Keyboard panel spells the modes: tilde, linux, xtermr6,\n\
;    vt400, vt100p, sco, xterm216. \"xterm216\" is the one worth setting - it\n\
;    is the only mode in which Shift+F1..F12 mean F13..F24 the way terminfo\n\
;    and every modern host expect.\n\
;funkeys=xterm216\n\
\n\
; verifyagent: a signed KiTTY checks, once per terminal window, whether the\n\
;    program answering its SSH agent requests is a verified KiTTY/kageant\n\
;    build, and warns when it is not. Set no if you deliberately run stock\n\
;    Pageant, the Windows OpenSSH agent or another agent. Also a checkbox:\n\
;    Connection -> SSH -> Auth (an application-wide setting, not per session).\n\
;verifyagent=yes\n\
\n\
; WorkplaceProxy / WorkplaceMinutes: the workplace-proxy-mode droplists'\n\
;    remembered LAST selection (which proxy, for how long), shared between\n\
;    the config box and the launcher menu so both offer the same thing next\n\
;    time. KiTTY writes these itself - not knobs to edit by hand, and NOT\n\
;    the mode's state: arming lives only in the running launcher.\n\
;WorkplaceProxy=\n\
;WorkplaceMinutes=240\n\
\n\
; PSCPPath: the full path to the file-copy helper - kscp.exe, or PuTTY's\n\
;    pscp.exe - used by drag-and-drop upload and the Send/Get file commands.\n\
;    You do not normally set this: KiTTY looks for the tool at startup and\n\
;    writes what it found back here. It searches, in order:\n\
;      1. this key, if it still points at a file that exists\n\
;      2. the pscpdir directory, kscp.exe first, then pscp.exe\n\
;      3. kscp.exe beside kitty.exe - the usual answer, since kscp ships\n\
;         with KiTTY and lives in the same folder\n\
;      4. %ProgramFiles%\\PuTTY\\pscp.exe\n\
;      5. pscp.exe beside kitty.exe\n\
;    A value naming a file that has gone away is dropped and the search runs\n\
;    again, so moving KiTTY does not leave it pointing at nothing. Set it by\n\
;    hand only to force a particular binary.\n\
;PSCPPath=\n\
\n\
; pscpdir: legacy fallback directory containing pscp.exe/kscp.exe (prefer PSCPPath)\n\
;pscpdir=\n\
\n\
; pscpport: the port kscp/pscp connects to for file transfer. Leave it unset\n\
;    and the transfer follows the SESSION's port - a host on 2222 transfers on\n\
;    2222, no second place to keep in step. * says the same thing explicitly.\n\
;    Give a number only to pin transfers to one port regardless of the session.\n\
;    (The old \"22\" shown here was wrong: unset has never meant 22.)\n\
;pscpport=*\n\
\n\
; ReconnectDelay: the delay before trying to reconnect automatically (in seconds)\n\
;ReconnectDelay=5\n\
\n\
; readonly: refuse to write to the CONFIGURATION FILE side of the settings.\n\
;    With yes, KiTTY will not write or delete entries in kitty.ini, will not\n\
;    create kitty.ini if it is missing, will not create the store's\n\
;    directories, and will not remove a legacy plaintext password it finds\n\
;    in the file. The configuration box says so instead of failing quietly.\n\
;    Not the same as conf=no, which is about KiTTY maintaining its OWN files\n\
;    (auto-creating kitty.ini, the kitty.sav and portable backups). readonly\n\
;    is the broader \"do not write\", and it covers deletes and directory\n\
;    creation as well.\n\
;    ⚠ Two things it does NOT do, despite the name: saved SESSIONS can still\n\
;    be written - they go through the session store, not this path - and in\n\
;    registry mode global settings are still written to the registry. Today\n\
;    it protects the ini file, not everything KiTTY stores.\n\
;readonly=no\n\
\n\
; restrictacl: apply the restricted process ACL to every KiTTY process, so you\n\
;    do not have to add -restrict-acl to each shortcut target. It denies other\n\
;    processes running as you the access rights used to read or write another\n\
;    process's memory - the same hardening as the -restrict-acl switch - and it\n\
;    propagates to the windows KiTTY spawns for you (config-box Start/Open,\n\
;    duplicate session, the launcher). kageant reads it too, so the process\n\
;    holding your loaded private keys is covered by the same setting.\n\
;    kittygen is not: pass it -restrict-acl if you want it hardened.\n\
;    Off by default, because it also blocks\n\
;    legitimate uses, notably screen readers and other accessibility tools.\n\
;    Worth knowing before an upgrade: an in-place MSI install will NOT reopen\n\
;    your sessions while this is on. Windows' Restart Manager cannot inspect\n\
;    a restricted process, so the installer closes those windows and cannot\n\
;    put them back. That is the hardening working as intended, not a fault in\n\
;    the installer - the whole point is that other processes running as you\n\
;    cannot reach into KiTTY, and the Restart Manager is one of them.\n\
;    yes is the only value that does anything: a process cannot un-restrict\n\
;    itself, so restrictacl=no does not lift a restriction already applied by\n\
;    -restrict-acl. If the ACL cannot be applied, KiTTY reports the error and\n\
;    exits rather than run unprotected.\n\
;    Unlike most keys here, this one is read from kitty.ini ONLY, never from\n\
;    the registry: the usual order consults the registry first, which would\n\
;    let a stale registry value silently cancel a restrictacl=yes written here.\n\
;restrictacl=no\n\
\n\
; sav: base path for the registry backup (a full export of KiTTY's hive). Each\n\
;    save writes a FRESH timestamped file next to it, <base>-YYYYMMDD-HHMMSS<ext>,\n\
;    so the filename always reflects when that copy was written. Default base is\n\
;    %APPDATA%\\KiTTY\\kittynew.sav (i.e. the files are kittynew-YYYYMMDD-HHMMSS.sav)\n\
;    - NOT kitty.sav, so an old 0.76 KiTTY's backup is never touched. A legacy\n\
;    value ending in kitty.sav or kitty084.sav is ignored so this default takes\n\
;    over; uncomment with a real path to force one.\n\
;    Backups left by earlier 0.84 builds (kitty-YYYYMMDD-HHMMSS.sav, from a\n\
;    defect that made the default kitty.sav after all) are still READ for a\n\
;    first-run restore; new ones are only ever written under the name above.\n\
;sav=\n\
\n\
; savbackupcount: in registry mode, how many timestamped backups to keep - the\n\
;    newest N are kept, older ones deleted. Default 5, max 50; 0 disables backups.\n\
;savbackupcount=5\n\
\n\
; savemode: where sessions are stored. Read from kitty.ini only - never from\n\
;    the registry, since the registry cannot say \"do not use the registry\".\n\
;    Allowed values are:\n\
;    - registry : sessions in the Windows registry, under KiTTY's own hive.\n\
;                 The default.\n\
;    - dir      : sessions as files in a directory tree, one file each. This\n\
;                 is portable mode: it also turns on folder browsing and the\n\
;                 portable password protection described further down.\n\
;    - file     : NOT a file backend, despite the name. Sessions still live\n\
;                 in the registry exactly as in registry mode; all it adds is\n\
;                 importing the .sav registry dump at startup when the hive is\n\
;                 missing. Upstream KiTTY abandoned this mode years ago and\n\
;                 marked it unmaintained; we kept it working as it is and are\n\
;                 not developing it further. It is not a half-finished feature\n\
;                 waiting to land - if you want sessions in files, use dir.\n\
;savemode=registry\n\
\n\
; portablebackupcount: in portable dir mode, keep this many timestamped backups\n\
;    under Backups\\kitty-portable-YYYYMMDD-HHMMSS. 0 disables portable backups.\n\
;portablebackupcount=5\n\
\n\
; PortablePasswordProtection: at-rest protection for passwords saved in portable\n\
;    (savemode=dir) session files. Only applies in portable mode; in registry\n\
;    mode saved passwords are always protected with Windows DPAPI.\n\
;    Allowed values are:\n\
;    - master : protect saved passwords with a master password (default). Only\n\
;               the password fields are encrypted, the rest of the session file\n\
;               stays readable. Copy the files and know the master password to\n\
;               use them on another machine. KiTTY asks you to set the master\n\
;               password the first time it saves a password; -masterpwfile\n\
;               supplies it without a prompt.\n\
;    - dpapi  : protect saved passwords with Windows DPAPI, i.e. this Windows\n\
;               account on this PC. No master password is created and KiTTY\n\
;               never asks for one - so unattended runs need no switch at all -\n\
;               but the passwords do NOT travel: copied to another PC or account\n\
;               they cannot be decrypted. Cannot be combined with -masterpwfile.\n\
;    - legacy : store saved passwords unprotected (plain text) for explicit\n\
;               compatibility/automation/audit setups. INSECURE - anyone who can\n\
;               read the files gets the passwords.\n\
;PortablePasswordProtection=master\n\
\n\
; WarnLegacyPasswordUpgrade: in portable mode, warn before a save re-encrypts a\n\
;    password stored in the old unprotected format into the new protected format\n\
;    (old KiTTY releases cannot read the new format). Set to no to skip the\n\
;    warning and re-encrypt silently; the warning dialog can also set this.\n\
;WarnLegacyPasswordUpgrade=yes\n\
\n\
; scriptfilefilter: file-dialog filter for local script files.\n\
;    Default: (*.ksh,*.sh)|*.ksh;*.sh|SQL files (*.sql)|*.sql|All files (*.*)|*.*|\n\
;    The example line below narrows it to all files only:\n\
;scriptfilefilter=All files (*.*)|*.*|\n\
\n\
; scriptmode: master switch for the RuTTY script engine (send a script file\n\
;    line by line, with wait-for-prompt/halt-on patterns). no = disable the\n\
;    engine entirely: the session auto-script does not run and the\n\
;    \"Send a script file\" menu entry refuses with a notice.\n\
;scriptmode=yes\n\
\n\
; shortcuts: enable/disable KiTTY's keyboard shortcuts. These are the ones\n\
;    that work in a TERMINAL WINDOW - the [Shortcuts] section below binds\n\
;    them, and they are what the Ctrl+Shift+letter predefined commands ride\n\
;    on. Set no if they clash with a full-screen program inside the terminal\n\
;    (Midnight Commander is the usual example) and the key should reach the\n\
;    host instead.\n\
;    It does not affect the configuration box: Ctrl+F and Ctrl+G there are a\n\
;    separate mechanism and keep working either way. Nor does it affect the\n\
;    per-session global hotkey, which is registered with Windows.\n\
;shortcuts=yes\n\
\n\
; size: append the live terminal size, e.g. [24x80] (rows x columns), to the\n\
;    window title. Updates as you resize; hidden while maximized. Needs\n\
;    wintitle=yes (the default).\n\
;size=no\n\
\n\
; slidedelay: the GLOBAL FALLBACK for how long each background image is shown,\n\
;    in seconds, when the background is a folder of images. It applies to every\n\
;    session that does not set its own interval; a session that does (the\n\
;    \"Slideshow:\" box under Window > Back.Image) always wins, and this value is\n\
;    then not consulted at all. 0 or unset means no timer - the image only\n\
;    changes when you ask for the next one. Nothing happens unless bgimage is\n\
;    on and the session actually has a background image.\n\
;slidedelay=0\n\
\n\
; shrinkbitmap: better quality when a background image has to be made smaller.\n\
;    It applies to ONE image placement: \"Stretch+\" under Window > Back.Image >\n\
;    Image placement - the placement whose whole job is fitting the image to\n\
;    the window. Tile, Center, Stretch, Absolute and Blank ignore this key.\n\
;    With Stretch+, and only when the image is larger than the window in both\n\
;    directions, KiTTY resamples it down instead of letting Windows\n\
;    stretch-blit it: visibly cleaner, slightly more work per repaint. On by\n\
;    default; set no to get the plain fast stretch back.\n\
;shrinkbitmap=no\n\
\n\
; sshversion: the client version string KiTTY announces to the SSH server.\n\
;    Default (unset): PuTTY-KiTTY - KiTTY's own identifier. Some servers reject a\n\
;    non-standard client-version string; set this to a common OpenSSH banner so\n\
;    KiTTY looks like a stock client. Use a current OpenSSH version, e.g.:\n\
;sshversion=OpenSSH_10.0\n\
\n\
; transparency: offer the window-transparency controls. On by default, and\n\
;    offering them is not using them - every session starts fully opaque.\n\
;    The level itself is PER SESSION, not set here. It lives in the\n\
;    configuration box under Window > Transparency, as a single\n\
;    \"Transparency:\" box, and is also reachable live from the window menu\n\
;    (Transparency + / -) and with Ctrl+Up / Ctrl+Down.\n\
;      0   fully opaque, and the default for a new session. The controls\n\
;          still work, so you can dim the window and bring it back.\n\
;      255 as see-through as it goes.\n\
;      -1  opaque, and locked that way. Nothing will dim the window: the\n\
;          keyboard refuses, the window menu does not even offer the\n\
;          Transparency entries, and the /transparency command declines.\n\
;          Pick it when an accidental Ctrl+Down must never dim this session.\n\
;          On screen 0 and -1 look the same - neither is translucent.\n\
;    If the panel is not in your configuration box, either this key is set to\n\
;    no or KiTTY is running in PuTTY mode - both hide it.\n\
;    Set no and transparency is off everywhere, not merely out of reach: the\n\
;    panel and the menu entries go, and a session that has a level saved opens\n\
;    opaque anyway. The /transparency command cannot turn it back on either.\n\
;transparency=yes\n\
\n\
; userpasssshnosave: do not keep the username and password KiTTY learned during\n\
;    a login in the running session's settings. They are then not carried into\n\
;    a duplicated session and cannot be written out if the session is saved.\n\
;    Default no. It does not remove or ignore a password you deliberately\n\
;    stored in a saved session - that one is still used to log in.\n\
;userpasssshnosave=no\n\
\n\
; winroll: double-click the title bar to roll the window up into the title bar\n\
;   alone, and double-click again to restore it. Ctrl+F12 does the same (see\n\
;   [Shortcuts] rollup), as does the /winroll command.\n\
;winroll=yes\n\
\n\
; WinSCPPath: the full path to the winscp.exe binary:\n\
;WinSCPPath=\n\
\n\
; winscpdir: legacy fallback directory containing WinSCP.exe (prefer WinSCPPath)\n\
;winscpdir=\n\
\n\
; wintitle: enable KiTTY's window-title decorations: the live size suffix\n\
;    (size=yes) and the (PROTECTED) / (ONTOP) status markers. no = plain stock\n\
;    titles. Unlike classic KiTTY the title text is never parsed, only\n\
;    decorated - the old remote title-command channel stays removed.\n\
;wintitle=yes\n\
\n\
; zmodem: enable ZModem transfers (the sz/rz commands). The switch gates both\n\
;   the ZModem Receive/Upload/Abort entries in the terminal's Tools menu and\n\
;   the Connection > ZModem configuration panel: with it off, neither appears.\n\
;   On by default; set it to no to hide both.\n\
;zmodem=yes\n\
\n\
\n\
\n\
[Shortcuts]\n\
\n\
; This section holds two separate mechanisms that happen to share it.\n\
;\n\
; FIRST: type this text for me. Pick any key combination, and pressing it\n\
; types a piece of text into the session instead of reaching the host. It takes\n\
; two lines - name the combination in \"list\", then give it a line of its own\n\
; saying what to type:\n\
;\n\
;      list={F5} {CONTROL}{F6}\n\
;      {F5}=uptime\\n\n\
;      {CONTROL}{F6}=cd /var/log\\n\n\
;\n\
; F5 now types \"uptime\" and presses Enter for you. \"list\" is what switches a\n\
; key on: a {F5}= line whose key is not named in list is simply ignored, which\n\
; is also how you park a definition without deleting it. Separate the names\n\
; with spaces.\n\
; In the text, \\n presses Enter, \\t is Tab, \\h is Backspace, \\p waits a second,\n\
; \\s05 waits five, and \\\\ is a literal backslash.\n\
;list={F5} {CONTROL}{F6}\n\
\n\
; SECOND: the named actions below. These are KiTTY's own functions - roll the\n\
; window up, send it to the tray, print the buffer - and each line changes the\n\
; key that triggers one. They are not text: the name on the left is the action,\n\
; and the value on the right is the key you want for it.\n\
;\n\
; Write a combination as modifiers then the key, each in braces:\n\
; {CONTROL}{SHIFT}{F4}, {ALT}{HOME}, {CONTROL}{F5}. Modifiers are {CONTROL}\n\
; {SHIFT} {ALT} {ALTGR} {WIN}; a plain letter or digit needs no braces\n\
; ({CONTROL}{ALT}T). An empty value takes the key away and leaves the action\n\
; with none; a combination KiTTY cannot parse falls back to the default.\n\
;\n\
; Each entry below says its default key. About a third say \"no default key\"\n\
; instead: those actions are real and work, but nothing is bound to them out of\n\
; the box, so they do nothing until you put a combination here. Most of them\n\
; are also on the window menu, which is how they are reachable at all today.\n\
;\n\
; How to write one:  {CONTROL}{SHIFT}L  {ALT}F4  {SHIFT}F12  - modifiers first,\n\
; in braces, then the key. So:\n\
;    openlogfile={CONTROL}{SHIFT}L      open this session's log file\n\
;    eventlog={CONTROL}{SHIFT}E         show the event log\n\
;\n\
; Two things worth knowing before you pick a combination:\n\
;  - Ctrl+Shift+<letter> is also where the predefined user commands live, but\n\
;    a binding here WINS: the user-command keys are tried last, and only when\n\
;    a command is actually defined in that slot. The cost is the other way\n\
;    round - binding Ctrl+Shift+L here means the 12th user command can no\n\
;    longer be reached by keyboard, only from its menu.\n\
;  - shortcuts=no in [KiTTY] switches this whole section off.\n\
\n\
; (re)send automatic command (default is SHIFT+F12)\n\
;autocommand=\n\
\n\
; Change settings ...\n\
;    No default key - it does nothing until you set one here.\n\
;changesettings=\n\
\n\
; Clear scrollback\n\
;    No default key - it does nothing until you set one here.\n\
;clearscrollback=\n\
\n\
; Clear the log file - or start a new one\n\
;    Which of the two it does depends on the log file name in\n\
;    Session > Logging. A fixed name (kitty.log) can only be emptied, so it is\n\
;    emptied. A name with a time in it (kitty_&T.log) gives a different file\n\
;    each time, so a new one is started and the old one is kept - the window\n\
;    menu says which it is about to do.\n\
;    No default key - it does nothing until you set one here.\n\
;    Example:  clearlogfile={CONTROL}{SHIFT}K\n\
;clearlogfile=\n\
\n\
; Open the log file of this session\n\
;    Opens the file this session is logging to, in whatever your system opens\n\
;    .log files with. Nothing happens if the session is not logging.\n\
;    No default key - it does nothing until you set one here.\n\
;    Example:  openlogfile={CONTROL}{SHIFT}L\n\
;openlogfile=\n\
\n\
; Close and restart current session\n\
;    No default key - it does nothing until you set one here.\n\
;closerestart=\n\
\n\
; run a local command (default is CONTROL+F5)\n\
;command=\n\
\n\
; Copy all window buffers to clipboard\n\
;    No default key - it does nothing until you set one here.\n\
;copyall=\n\
\n\
; Open a duplicate window (with same session settings)\n\
;    (default is CONTROL+ALT+T)\n\
;duplicate=\n\
\n\
; open text editor connected to the main window (default is SHIFT+F2)\n\
;editor=\n\
\n\
; open text editor with clipboard content, connected to the main window (default is CONTROL+SHIFT+F2)\n\
;editorclipboard=\n\
\n\
; Show event log\n\
;    KiTTY's own record of what the connection did - not the session log.\n\
;    No default key - it does nothing until you set one here.\n\
;    Example:  eventlog={CONTROL}{SHIFT}E\n\
;eventlog=\n\
\n\
; Switch font to black on white colors\n\
;    No default key - it does nothing until you set one here.\n\
;fontblackandwhite=\n\
\n\
; Decrease font size\n\
;    No default key - it does nothing until you set one here.\n\
;fontdown=\n\
\n\
; Switch font to negative colors\n\
;    No default key - it does nothing until you set one here.\n\
;fontnegative=\n\
\n\
; Increase font size\n\
;    No default key - it does nothing until you set one here.\n\
;fontup=\n\
\n\
; Switch to full screen\n\
;    No default key - it does nothing until you set one here.\n\
;fullscreen=\n\
\n\
; receive a remote file with pscp.exe: the full path must be selected in clipboard (default is CONTROL+F4)\n\
;getfile=\n\
\n\
; change the background image (default is CONTROL+F11)\n\
;imagechange=\n\
\n\
; special command box (default is CONTROL+F8)\n\
;input=\n\
\n\
; special command with multi-line editor (default is SHIFT+F8)\n\
;inputm=\n\
\n\
; Repeat key exchange\n\
;    No default key - it does nothing until you set one here.\n\
;keyexchange=\n\
\n\
; New session ...\n\
;    No default key - it does nothing until you set one here.\n\
;opennew=\n\
\n\
; Inherit New Session: a new configuration box carrying the current settings.\n\
;    In quick connect (see [ConfigBox] loadlastsession) the host name comes with\n\
;    them, selected and ready to be edited into the next machine; otherwise the\n\
;    box opens without a host.\n\
;    No default key - it does nothing until you set one here.\n\
;opennewcurrent=\n\
\n\
; Print current clipboard content (default is SHIFT+F7)\n\
;print=\n\
\n\
; Print all window buffer content (default is F7)\n\
;printall=\n\
\n\
; Protect the window, disable keyboard and mouse input (default is CONTROL+F9)\n\
;protect=\n\
\n\
; Reset terminal\n\
;    No default key - it does nothing until you set one here.\n\
;resetterminal=\n\
\n\
; Roll-up the window into the title bar (default is CONTROL+F12)\n\
;rollup=\n\
\n\
; Load a local script and run it remotely (default is CONTROL+F2)\n\
;script=\n\
\n\
; Send a local file with pscp.exe (default is CONTROL+F3)\n\
;sendfile=\n\
\n\
; Show current port forwarding definition (default is SHIFT+F6)\n\
;showportforward=\n\
\n\
; Enable or disable logging (default is SHIFT+F5)\n\
;switchlogmode=\n\
\n\
; Send the window to the system tray (default is CONTROL+F6)\n\
;tray=\n\
\n\
; Switch to embedded image viewer (default SHIFT+F11)\n\
;viewer=\n\
\n\
; Switch to always visible (default is CONTROL+F7)\n\
;visible=\n\
\n\
; Start WinSCP (default is SHIFT+F3)\n\
;winscp=\n\
\n\
\n\
\n\
[Print]\n\
\n\
; height: the vertical distance between printed lines, in printer device\n\
;    units - each line is drawn at line number x this value, so it is a line\n\
;    pitch rather than a font size. Raising it spaces the printout out;\n\
;    lowering it packs it. The font itself is the terminal's.\n\
;height=100\n\
\n\
; maxline: how many lines go on a page before a new one is started.\n\
;maxline=60\n\
\n\
; maxchar: where a long line is wrapped onto the next printed line. It wraps\n\
;    rather than truncating, so nothing is lost.\n\
;maxchar=85\n\
\n\
\n\
\n\
[Launcher]\n\
\n\
; alreadyRunCheck: what a second launcher does when one is already running.\n\
;    Unset (the default) the second one exits silently. yes = exit as well,\n\
;    stated explicitly. Any other value lets it start anyway, which is only\n\
;    useful when you deliberately want two launcher windows.\n\
;    One case ignores this setting entirely: a launcher started to HOLD\n\
;    workplace proxy mode. The launcher window class is shared by every\n\
;    KiTTY on the machine, while workplace mode is per installation - so a\n\
;    portable copy or a second install already in the tray owns that class,\n\
;    and a launcher started to arm OUR install would exit here without\n\
;    arming anything. Holding the arming therefore exempts it from the\n\
;    check. Two launchers of the SAME install still cannot both arm: the\n\
;    arming refuses a second holder, and that one exits like any duplicate.\n\
;alreadyRunCheck=yes\n\
\n\
; classname: override the Win32 window class the launcher registers and\n\
;    looks for. Only worth setting to keep two KiTTY installations from\n\
;    recognising each other as \"already running\".\n\
;classname=KiTTYLauncher\n\
\n\
; reload: rebuild the launcher's session list each time its menu is opened,\n\
;    so sessions saved since it started appear. On by default; only the value\n\
;    no turns it off, and then the list is the one read at launcher startup.\n\
;reload=yes\n\
\n\
; exitwithworkplace: close the launcher again when workplace proxy mode is\n\
; switched off (default yes). Only applies to a launcher that the mode itself\n\
; started, by switching the mode on when none was running - a launcher you\n\
; started yourself always keeps running, because it is also your session list\n\
; and your hotkeys. Set no to keep the started one too.\n\
;exitwithworkplace=yes\n\
\n\
; noticeseconds: how long the workplace proxy mode notice stays on screen\n\
; (default 15). It is a window of our own rather than a tray balloon precisely\n\
; so that this is ours to set: Windows has ignored the requested balloon\n\
; duration since Vista, and a balloon cannot carry the mode's colour.\n\
;noticeseconds=15\n\
\n\
\n\
[Agent]\n\
\n\
; kageant (the SSH agent) settings. kageant finds this file on its own:\n\
; %KITTY_INI_FILE%, else kitty.ini/putty.ini next to kageant.exe, else\n\
; %APPDATA%\\KiTTY\\kitty.ini / %APPDATA%\\PuTTY\\putty.ini. When the file\n\
; says [KiTTY] savemode=file or savemode=dir, the ini is the authoritative\n\
; store: the tray toggles write back here and the registry is never touched\n\
; (portable mode). A portable folder counts even without the savemode\n\
; line: with savemode absent, a Sessions folder or KiTTYState file next\n\
; to the ini also makes it authoritative. Otherwise (savemode=registry,\n\
; or absent with no such layout) the registry stays authoritative and\n\
; these keys act as first-run defaults only.\n\
\n\
; askconfirmation: prompt before a loaded key may sign:\n\
;   yes  = every key use\n\
;   auto = only keys whose comment contains \"confirmation\" (default)\n\
;   no   = never - also disables the per-key comment prompts (automation)\n\
;askconfirmation=auto\n\
\n\
; messageonkeyusage: a notice naming the key after each signature - kageant's\n\
;    own small window, not a tray balloon (Windows suppresses those under\n\
;    focus assist, which for a security notice is the worst way to fail). It\n\
;    names the key by comment and by fingerprint, since two keys can share a\n\
;    comment.\n\
; messageonkeyusage covers key USE (signatures) and, over IPC, key ADD /\n\
; REMOVE / REMOVE-ALL naming the requesting program - a notice, never a\n\
; prompt, so it does not break scripted ssh-add.\n\
;messageonkeyusage=yes\n\
\n\
; noticetimeout: how long the kageant notices stay on screen, in\n\
; seconds (2-120). One knob for all of them (key used, key added/\n\
; removed over IPC, startup keys missing). Absent = each notice's own\n\
; default. Hovering the pointer over a notice holds it open regardless.\n\
;noticetimeout=8\n\
\n\
; --- IPC access control (all default no). These restrict only requests\n\
; that arrive from OTHER programs over the agent protocol (WM_COPYDATA /\n\
; the named pipe, which is also what the Windows-OpenSSH integration\n\
; uses); the kageant window's own Add/Remove buttons are never affected.\n\
; Signing and listing keys are always allowed; re-encrypting a key is\n\
; allowed even under lockdown (it only tightens a key by dropping its\n\
; cleartext).\n\
; lockdownmode: refuse ALL key add/remove/remove-all over IPC.\n\
;lockdownmode=no\n\
; blockipcadd / blockipcremove: refuse just adds, or just removes.\n\
;blockipcadd=no\n\
;blockipcremove=no\n\
\n\
; loadkeysonstartup: re-add the remembered keys when kageant starts, added\n\
;    encrypted so the passphrase is asked on first use, not at login. Only the\n\
;    key FILE PATHS are remembered - never a passphrase or key material - and\n\
;    the list below is maintained for you as you add and remove keys.\n\
;    Off by default. Was called loadonstartup; the old name is read once and\n\
;    rewritten under this one.\n\
;    This is its own tray item and its own Settings checkbox, \"Load remembered\n\
;    keys at startup\". Starting kageant at login is a separate switch beside\n\
;    it, and whether THAT looks ticked is decided by the autostart artifact -\n\
;    the Run entry or Startup shortcut, checked to point at this kageant - not\n\
;    by any setting in this file.\n\
;loadkeysonstartup=no\n\
\n\
; startupkey1, startupkey2, ...: the remembered key files, in order. Paths\n\
; under this install folder are stored relative to it (so they travel); a\n\
; trailing \",encrypted\" loads that key deferred. kageant writes these when\n\
; you load keys with loadkeysonstartup on - not knobs to edit by hand.\n\
;startupkey1=keys\\id_ed25519.ppk,encrypted\n\
\n\
; --- Startup keys on removable media.\n\
; retrykeys: when a drive appears, load the startup keys that were not there\n\
; at login (they wait as \"not loaded\" rows in the key list rather than being\n\
; dropped). Default yes - it does nothing unless a startup key is actually\n\
; missing.\n\
;retrykeys=yes\n\
; unloadonremove: when the media a key came from goes away, drop that key\n\
; from the agent and put it back on the pending list, so it returns when the\n\
; media does. Default no, deliberately: pulling a stick must not break an\n\
; authentication that is running right now.\n\
;unloadonremove=no\n\
; quietmissingkeys: skip the startup notice that counts keys whose media is\n\
; absent (expected, when they live on a stick that is not always plugged\n\
; in). A key file that EXISTS but will not load is still reported - that is\n\
; a broken key, not an absent one.\n\
;quietmissingkeys=no\n\
\n\
; passphrasecacheseconds: how long a typed passphrase is kept (encrypted in\n\
; memory) to unlock further keys of a batch add without retyping it.\n\
; 0 = do not cache; capped at 300. Default 60.\n\
;passphrasecacheseconds=60\n\
\n\
; keylistgeometry / keylistcolumns: the key-list window's remembered\n\
; position/size and column widths. kageant writes these itself when the\n\
; window is moved, resized or closed - not knobs to edit by hand.\n\
;keylistgeometry=\n\
;keylistcolumns=\n\
\n\
\n\
[FontFallback]\n\
\n\
; Font fallback: when the terminal font is missing a character (box drawing,\n\
; Nerd Font icons, CJK, symbols...), KiTTY probes a list of fallback fonts\n\
; and draws that character from the first font that has it. Cell widths are\n\
; unchanged; only the glyph's source font differs. Rendering is plain GDI,\n\
; so emoji come out monochrome. NB: section and key names in this file are\n\
; case-sensitive.\n\
\n\
; active: master switch for the whole feature\n\
;active=yes\n\
\n\
; fallback: comma-separated list of font names to try, in order, before the\n\
; built-in defaults (Cascadia Mono, Cascadia Code, Segoe UI Symbol, Segoe UI\n\
; Emoji, Segoe UI Historic, Microsoft YaHei UI, Microsoft JhengHei UI,\n\
; Yu Gothic UI, Malgun Gothic). Naming a built-in just promotes it. Fonts\n\
; that are not installed are skipped. Start the list with ! to REPLACE the\n\
; built-in defaults instead.\n\
;    Example:  fallback=Symbols Nerd Font Mono,JetBrains Mono\n\
;                 try those two first, then fall through to the built-in list\n\
;    Example:  fallback=!MyOnlyFont1,MyOnlyFont2\n\
;                 the leading ! drops the built-in list: only these two are\n\
;                 tried, so a character neither font has stays a blank box\n\
;    Default is empty - the built-in list above is used as it stands.\n\
;fallback=\n\
\n\
; override: force a Unicode range (or single codepoint, hex) to a specific\n\
; font regardless of probe results; multiple entries separated by ;\n\
;override=E000-F8FF:Symbols Nerd Font Mono;1F600-1F64F:Segoe UI Emoji\n\
\n\
; log: off|error|warn|info|debug|trace - troubleshooting log for the fallback\n\
;    probing. Written to fontfallback.log in the folder the running\n\
;    executable sits in unless logfile says otherwise (see the note there\n\
;    about that folder not always being writable). debug and trace are high\n\
;    volume - a busy session writes megabytes.\n\
;log=off\n\
\n\
; logfile: where to write that log instead of the default. Unset, it goes to\n\
;    fontfallback.log in the folder the running executable sits in - which is\n\
;    read-only for a normal user under Program Files, so a per-user install or\n\
;    a portable copy gets the file and an installed one may not. Give a full\n\
;    path to put it somewhere writable, e.g. %USERPROFILE%\\fontfallback.log\n\
;    spelled out (this file does not expand environment variables).\n\
;    The file is appended to, and one previous copy is kept alongside it\n\
;    with a .1 suffix.\n\
;logfile=\n\
" ;
