/*
 * kitty_selfcheck.c - the third startup guard: does this file still match
 * the stamp it was released with? See kitty_selfcheck.h for the contract and
 * kitty_selfcheck_core.h for the stamp layout and the hash rule, which the
 * release stamp tool shares byte for byte.
 *
 * NOT in `utils`: the check needs ssh_sha256 and the Ed25519 verify from
 * `crypto`, which comes BEFORE `utils` in the single-pass static link, and
 * psocks links utils without any crypto at all. So this file is listed on
 * each target that opts in (kitty, kitty_portable, plink, pscp, psftp) and
 * on nothing else.
 *
 * Windows XP era on purpose, like the other guards: CreateFileA, ReadFile,
 * SetFilePointer, GetStartupInfoA, GetEnvironmentVariableA. The file is read
 * in fixed-size chunks into STACK buffers - no heap for the file, no mapping -
 * so a job object's memory limit or a hostile environment cannot manufacture
 * a "cannot check" out of thin air; what is left is the own file not being
 * openable, which for a running program means its path is gone or unreadable.
 */
#include <windows.h>
#include <stdio.h>
#include <string.h>

#include "putty.h"
#include "kitty_selfcheck.h"
#include "kitty_renameguard.h"   /* kitty_guard_interactive, kitty_guard_report */
#include "kitty_text.h"

#ifdef KITTY_SELFCHECK

#include "kitty_selfcheck_core.h"

/*
 * The public key of THIS release, generated by the release run into a header
 * outside the repository (default: kitty_selfcheck_key.h in the build
 * directory; the build passes another path as KITTY_SELFCHECK_KEY_HEADER).
 * It defines KITTY_SELFCHECK_PUBKEY_BYTES as a 32-byte initialiser list.
 *
 * Deliberately a plain constant with no marker around it: the key bytes are
 * random per release, and nothing in the file points at them.
 */
#ifdef KITTY_SELFCHECK_KEY_HEADER
#include KITTY_SELFCHECK_KEY_HEADER
#else
#include "kitty_selfcheck_key.h"
#endif
static const unsigned char kt_pubkey[KT_ED25519_PUB_LEN] =
    KITTY_SELFCHECK_PUBKEY_BYTES;

/* The stamp block itself - the 256 bytes in the `.ktstamp` section the stamp
 * tool fills - is defined in kitty_selfcheck_stamp.c, a translation unit of
 * its own without any crypto dependency, so that every shipped program can
 * carry the stamp, including the two that link no crypto library and cannot
 * run this check (pterm, puttytel). The own-image read below still names it,
 * which is also what keeps every linker from treating it as unreferenced. */
extern const unsigned char kt_stamp_block[KT_STAMP_SIZE];

#ifdef KITTY_SELFCHECK_FAULT
/*
 * Test builds only. The marker makes the build recognisable to the stamp
 * tool, which refuses to stamp it: the fault switch must never reach a
 * release. The switch itself is the environment variable of the same name.
 */
static const char kt_fault_marker[] __attribute__((used)) =
    KT_SELFCHECK_FAULT_MARKER;
static int kt_fault_armed(void)
{
    char v[8];
    return GetEnvironmentVariableA("KITTY_SELFCHECK_FAULT", v, sizeof(v)) > 0;
}
#else
#define kt_fault_armed() 0
#endif

/* Reader over a Win32 handle for kt_stamp_hash. */
static int kt_read_at(void *ctx, uint64_t off, void *buf, size_t len)
{
    HANDLE h = (HANDLE)ctx;
    LONG hi = (LONG)(off >> 32);
    DWORD got = 0;

    if (SetFilePointer(h, (LONG)(uint32_t)off, &hi, FILE_BEGIN) ==
            INVALID_SET_FILE_POINTER && GetLastError() != NO_ERROR)
        return 0;
    if (!ReadFile(h, buf, (DWORD)len, &got, NULL) || got != len)
        return 0;
    return 1;
}

/*
 * Visible, for the cannot-check decision. A windowed program is visible on a
 * visible window station AND when it was not started hidden - a copy started
 * with SW_HIDE on a user's desktop is the shape abuse takes, and KiTTY never
 * starts its own kitty.exe that way. A console program is judged by the
 * window station alone: KiTTY starts klink hidden for the host-key check and
 * kscp without a window for its transfer window, and both must keep running.
 */
static int kt_visible(int gui)
{
    if (!kitty_guard_interactive())
        return 0;
    if (gui) {
        STARTUPINFOA si;
        memset(&si, 0, sizeof(si));
        si.cb = sizeof(si);
        GetStartupInfoA(&si);
        if ((si.dwFlags & STARTF_USESHOWWINDOW) && si.wShowWindow == SW_HIDE)
            return 0;
    }
    return 1;
}

/*
 * The verdict on the file at `path`. Returns 0 = intact, 1 = refuse (reason
 * filled), 2 = cannot check (the caller decides by visibility). `own` says
 * the file is this process's own image, which adds the fault switch and the
 * check that the image's own stamp block is ours; `sha_out`, when given,
 * receives the recomputed hash (for a display).
 */
static int kt_verdict_path(const char *path, int own, const char **reason,
                           unsigned char *sha_out)
{
    HANDLE h;
    unsigned char hdr[4096];
    unsigned char stamp[KT_STAMP_SIZE];
    unsigned char chunk[KT_STAMP_CHUNK];
    unsigned char sha[KT_SHA256_LEN];
    kt_pe_layout lay;
    uint64_t length, filesize;
    DWORD sizelo, sizehi;
    int rc = 2;

    *reason = NULL;
    if (own) {
        if (kt_fault_armed())
            return 2;
        /* The image's own block must be ours; this is also the one read of the
         * block that keeps every linker from treating it as unreferenced. */
        if (memcmp(kt_stamp_block, KT_STAMP_MAGIC, KT_STAMP_MAGIC_LEN) != 0)
            return 2;
    }

    h = CreateFileA(path, GENERIC_READ,
                    FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,
                    NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (h == INVALID_HANDLE_VALUE)
        return 2;

    sizelo = GetFileSize(h, &sizehi);
    if (sizelo == INVALID_FILE_SIZE && GetLastError() != NO_ERROR)
        goto out;
    filesize = ((uint64_t)sizehi << 32) | sizelo;

    /* The headers: whatever fits, the file may be shorter than the buffer. */
    memset(hdr, 0, sizeof(hdr));
    if (!kt_read_at(h, 0, hdr, (size_t)((filesize < sizeof(hdr)) ?
                                        filesize : sizeof(hdr))))
        goto out;
    if (!kt_pe_parse(hdr, sizeof(hdr), &lay))
        goto out;

    /* From here on every failure is a finding about the FILE, not about the
     * check: the file opened and reads as a PE. */
    if (!lay.stamp_off || lay.stamp_off + KT_STAMP_SIZE > filesize) {
        *reason = "no stamp"; rc = 1; goto out;
    }
    if (!kt_read_at(h, lay.stamp_off, stamp, KT_STAMP_SIZE))
        goto out;
    if (!kt_stamp_is_filled(stamp) ||
            kt_le32(stamp + KT_STAMP_OFF_VERSION) != KT_STAMP_VERSION) {
        *reason = "no stamp"; rc = 1; goto out;
    }
    length = kt_le64(stamp + KT_STAMP_OFF_LENGTH);
    if (length > filesize) {
        *reason = "truncated"; rc = 1; goto out;
    }
    /* The stamp must lie inside what it covers, or it covers nothing. */
    if (lay.stamp_off + KT_STAMP_SIZE > length) {
        *reason = "bad stamp"; rc = 1; goto out;
    }
    if (!kt_ed25519_verify(kt_pubkey, stamp + KT_STAMP_OFF_SIG,
                           stamp, KT_STAMP_SIGNED_LEN)) {
        *reason = "bad stamp"; rc = 1; goto out;
    }
    if (!kt_stamp_hash(kt_read_at, (void *)h, &lay, length, chunk, sha))
        goto out;                                    /* read failed: 2 */
    if (sha_out)
        memcpy(sha_out, sha, KT_SHA256_LEN);
    if (memcmp(sha, stamp + KT_STAMP_OFF_SHA256, KT_SHA256_LEN) != 0) {
        *reason = "modified"; rc = 1; goto out;
    }
    rc = 0;

  out:
    CloseHandle(h);
    smemclr(chunk, sizeof(chunk));
    return rc;
}

static int kt_verdict(const char **reason)
{
    char path[MAX_PATH + 1];
    DWORD n = GetModuleFileNameA(NULL, path, sizeof(path) - 1);
    if (n == 0 || n >= sizeof(path) - 1)
        return 2;
    path[n] = '\0';
    return kt_verdict_path(path, 1, reason, NULL);
}

int kitty_selfcheck_file(const char *path, char *reason, size_t reasonsz,
                         char *sha_hex, size_t hexsz)
{
    const char *why = NULL;
    unsigned char sha[KT_SHA256_LEN];
    int rc;
    static const char hexd[] = "0123456789abcdef";
    if (reason && reasonsz) reason[0] = '\0';
    if (sha_hex && hexsz) sha_hex[0] = '\0';
    memset(sha, 0, sizeof(sha));
    rc = kt_verdict_path(path, 0, &why, sha);
    if (rc == 1 && reason && reasonsz) { strncpy(reason, why, reasonsz - 1); reason[reasonsz - 1] = '\0'; }
    if ((rc == 0 || (rc == 1 && why && !strcmp(why, "modified"))) && sha_hex && hexsz > 2 * KT_SHA256_LEN) {
        size_t i;
        for (i = 0; i < KT_SHA256_LEN; i++) { sha_hex[2 * i] = hexd[sha[i] >> 4]; sha_hex[2 * i + 1] = hexd[sha[i] & 15]; }
        sha_hex[2 * KT_SHA256_LEN] = '\0';
    }
    return rc;
}

int kitty_selfcheck_guard(int gui)
{
    static int decided = 0;
    static int verdict = 0;
    const char *reason;
    char msg[400];
    int v;

    if (decided)
        return verdict;
    decided = 1;

    v = kt_verdict(&reason);
    if (v == 0)
        return 0;
    if (v == 2) {
        if (kt_visible(gui))
            return 0;                /* cannot judge, somebody is there: run */
        reason = "cannot check";
        sprintf(msg, KT_SELFCHECK_GUARD_MSG, reason);
        /* Invisible by definition: the event log, and stderr for a console
         * program; never a box, which nobody could click. */
        kitty_guard_report(msg, gui, 0);
        verdict = 1;
        return 1;
    }
    sprintf(msg, KT_SELFCHECK_GUARD_MSG, reason);
    kitty_guard_report(msg, gui, 1);
    verdict = 1;
    return 1;
}

#else /* !KITTY_SELFCHECK */

/*
 * Dev and test builds carry no stamp, so there is nothing to check and
 * nothing of the check in the binary. The call sites stay unconditional: one
 * shape of startup code, and a build option decides whether it does anything.
 */
int kitty_selfcheck_guard(int gui)
{
    (void)gui;
    return 0;
}

int kitty_selfcheck_file(const char *path, char *reason, size_t reasonsz,
                         char *sha_hex, size_t hexsz)
{
    (void)path;
    if (reason && reasonsz) reason[0] = '\0';
    if (sha_hex && hexsz) sha_hex[0] = '\0';
    return 3;                          /* this build carries no key */
}

#endif /* KITTY_SELFCHECK */
