/* Generated by tools/gen-kitty-ini-template.py from
 * docs/examples/kitty.ini.example - do not edit by hand. This is the
 * kitty.ini KiTTY writes when it starts and finds none. */
char default_init_file_content[] = "; kitty.ini - KiTTY's settings file. This one was created by KiTTY itself,\n\
; because there was none; it is yours to edit.\n\
;\n\
; Every supported option is listed below, commented out, led by a description.\n\
; Nothing here is in force: uncomment a line to use it. The values shown are\n\
; the built-in defaults, so uncommenting a line unchanged does nothing today -\n\
; but it does pin that value, where a commented line keeps following the\n\
; default if a later KiTTY changes it.\n\
;\n\
; Some settings are also held in the registry, and outside portable mode the\n\
; registry is read first - so if an edit here seems to have no effect, that is\n\
; usually why. See\n\
;   https://github.com/hknet/KiTTY/blob/kitty-0.84/docs/KITTY-INI.md\n\
\n\
[ConfigBox]\n\
\n\
; dblclick: what a double-click on a saved session does\n\
;    - open: load it and open it in this window (like the Open button)\n\
;    - start: launch it in a new window and keep the configuration box open (like the Start button)\n\
;dblclick=open\n\
\n\
; defaultsettings: when no, 'Default Settings' is hidden from the saved-session\n\
;    list in the config box. The session itself is always there either way - it\n\
;    is the template every new session starts from - so this only decides\n\
;    whether you can see and click it. Default yes (shown, like stock PuTTY).\n\
;    Note it is also the way into quick connect, where you type a host instead\n\
;    of picking a session: you get there by loading Default Settings once. Hide\n\
;    the row and that route is gone unless you set loadlastsession=no below.\n\
;    https://github.com/hknet/KiTTY/blob/kitty-0.84/FEATURES.md#quick-connect-type-a-host-instead-of-picking-a-session\n\
;defaultsettings=yes\n\
\n\
; categoryexpand: how many levels of the config-box Category tree are expanded\n\
;    on open. Default (unset, or all/full) = fully expanded; a number expands only\n\
;    that deep - 1 = top categories only (stock PuTTY), 2 = one level of subtrees,\n\
;    and so on.\n\
;categoryexpand=all\n\
\n\
; filter: with yes (the default), typing in the Saved Sessions NAME BOX narrows\n\
;    the list below to sessions matching what you typed. no leaves the box as a\n\
;    plain name field and the list always shows everything, like stock PuTTY.\n\
;    Typing directly into the list is Windows' own first-letter jump and is not\n\
;    affected either way.\n\
;    Two keys go with it, from anywhere in the configuration box:\n\
;      Ctrl+F  jump to the Session panel and put the cursor in that name box,\n\
;              with what is already there selected so you can type over it.\n\
;              It searches within the folder currently selected.\n\
;      Ctrl+G  the same, but drops the folder filter back to the root list\n\
;              first - \"search everywhere\", for finding a session when you\n\
;              do not remember which folder it is in.\n\
;    Neither loads, moves or saves anything, and neither is affected by\n\
;    [KiTTY] shortcuts.\n\
;filter=yes\n\
\n\
; height: the number of visible lines in the saved-sessions list (default 16 = stock fit)\n\
;height=16\n\
\n\
; loadlastsession: when yes (default), the configuration box opens pre-filled with\n\
;    the session used last. When no, it opens on 'Default Settings' with the caret\n\
;    already in 'Host Name (or IP address)' - quick connect: type a host, press\n\
;    Enter, and every connection starts from the same known configuration instead\n\
;    of inheriting whatever was used before.\n\
;loadlastsession=yes\n\
\n\
; noexit: if yes, closing a window that ran a connected session starts a fresh\n\
;    instance showing the configuration box, so you land back in the session\n\
;    picker. A window that never connected (e.g. the config box itself was\n\
;    cancelled) exits normally, and nothing respawns during system shutdown.\n\
;noexit=no\n\
\n\
; proxyselection: show the named-proxy chooser in the Session panel.\n\
;   auto (default) = show once any named proxy is defined; yes = always; no = never\n\
;   Where you DEFINE one in the first place depends on this setting: with yes\n\
;   the chooser is always in the Session panel and carries an Edit button next\n\
;   to it. With auto the chooser stays hidden until a definition exists, so the\n\
;   way in is Connection > Proxy > \"Edit named proxies...\". no hides both, and\n\
;   nothing in the GUI can then create or edit a definition.\n\
;proxyselection=auto\n\
\n\
; windowheight: force the configuration window to an explicit height, in pixels\n\
;    (scaled for your display DPI). Default 0 = off, so the window is sized from\n\
;    [ConfigBox] height instead. This is a blunt override - it resizes only the\n\
;    outer window, not the inner controls - so [ConfigBox] height is usually what\n\
;    you want. Set a pixel value, e.g. 800, to force it.\n\
;windowheight=0\n\
\n\
\n\
\n\
[KiTTY]\n\
\n\
; antiidle: string sent to the server periodically to keep the connection alive.\n\
;    Default (unset/empty) = disabled. \\k08 sends a backspace; pick a sequence the\n\
;    remote ignores. Interval is set by antiidledelay (seconds).\n\
;antiidle=\\k08\\\n\
\n\
; antiidledelay: time delay between two sending\n\
;antiidledelay=60\n\
\n\
; autoreconnect: reconnect a session by itself when the link drops, retrying\n\
;    while the network is away. This is one of the premiere features users\n\
;    start using KiTTY for - a session disconnect is no longer a manual job to\n\
;    reconnect but solved by KiTTY for the user. On by default; see\n\
;    ReconnectDelay for how long it waits between attempts.\n\
;autoreconnect=yes\n\
\n\
; backgroundimage: enable/disable the background image feature\n\
;bgimage=no\n\
\n\
; bcdelay: delay in MILLISECONDS between each character in every automatic\n\
;    keyboard send (autocommand, login script, user commands, send-text boxes).\n\
;    Default 0 = off. Set a few ms (e.g. 3) for hosts that drop characters\n\
;    when input arrives too fast.\n\
;bcdelay=0\n\
\n\
; commanddelay: delay in SECONDS between two lines of the automatic start\n\
;    command script (Connection/Data/Command setting). 0.05 = 50 ms; minimum\n\
;    enforced 0.005.\n\
;commanddelay=0.05\n\
\n\
; conf: `no` stops KiTTY creating and maintaining its own files - kitty.ini is\n\
;   not auto-created, and neither the kitty.sav backup nor the portable-folder\n\
;   backups are written. Only `no` does anything: `conf=yes` is ignored rather\n\
;   than being a way to switch the behaviour back on. It is not remembered\n\
;   either - drop the line and the next start behaves normally.\n\
;   Yes, an option that says \"write no configuration file\" living IN the\n\
;   configuration file contradicts itself. Noted - and it still does what it\n\
;   advertises: no further writes to those files. If you want no kitty.ini at\n\
;   all, put the value in the registry instead - a string value conf = no\n\
;   under HKCU\\Software\\kapper.net\\KiTTY - and delete kitty.ini. Outside\n\
;   portable mode the registry is read first, so it is honoured from there.\n\
;conf=yes\n\
\n\
; configdir: where the settings directories live - Sessions, SshHostKeys and\n\
;    the rest. Portable mode uses it; by default it is the directory kitty.exe\n\
;    sits in.\n\
;    It does NOT move kitty.ini. This file has to be found before anything in\n\
;    it can be read, so KiTTY is already holding it by the time it learns where\n\
;    configdir points - kitty.ini stays where it was.\n\
;    Removing the setting later does not move anything back either: your\n\
;    sessions, host keys and stored keys stay in that directory and KiTTY stops\n\
;    looking there, so they simply disappear from the list. Before you unset or\n\
;    change it, use \"Export all...\" in the configuration box (Session panel),\n\
;    then change the setting, then \"Import all...\" - that carries everything\n\
;    across instead of stranding it.\n\
;configdir=\n\
\n\
; browsedirectory: base directory for portable/session file browsing; normally auto-detected\n\
;browsedirectory=\n\
\n\
; Folders: legacy session-folder cache, managed by KiTTY; edit only for recovery/debugging\n\
;Folders=\n\
\n\
; RootFolderLabel: what the configuration box's folder selector calls the root\n\
;    session list. That list is not \"the sessions in no folder\" - it is ALL\n\
;    of them: picking the root switches the folder filter off, so sessions\n\
;    filed in folders stay listed too. Which is why the built-in label says\n\
;    \"All sessions\". Display only - that\n\
;    folder is always stored as \"Default\", so renaming the label changes no\n\
;    session and no saved setting. Normally set from the config box itself:\n\
;    select the root list, type a new name over its label, press Rename; typing\n\
;    the built-in name back restores it. Like Folders, this is stored in\n\
;    whichever backend your save mode uses - the registry in registry mode,\n\
;    this file in file/dir mode.\n\
;RootFolderLabel=All sessions (root)\n\
\n\
; cryptsalt: set salt mode for password encryption\n\
;cryptsalt=1\n\
\n\
; CtHelperPath: the full path to the cthelper.exe binary (Wrapper for Cygwin feature)\n\
;CtHelperPath=\n\
\n\
; ctrltab: allow Ctrl+Tab to switch between open KiTTY windows. This is the\n\
;    master switch only - it does not turn the feature on by itself. Each\n\
;    session also has its own \"Switch KiTTY windows with Ctrl + TAB\" box in\n\
;    Window > Behaviour, which is off until you tick it, and that box is only\n\
;    offered while this is yes. no hides the box and disables the key; the\n\
;    -noctrltab command-line switch does the same for one window.\n\
;ctrltab=yes\n\
\n\
; debug: extra tracing in the Event Log - saved-session lookups, the automatic\n\
;    command, key remappings, the internal editor, and the pscp / WinSCP\n\
;    command lines actually run. The password those command lines carry is\n\
;    blanked in the log, but the host, user, paths and switches are not, so\n\
;    read a debug log before you send it to anyone.\n\
;    It also enables /passwd, which shows this session's password and copies\n\
;    it to the clipboard; without debug mode that command is treated as plain\n\
;    text and sent to the host instead. /debug turns all of this on and off at\n\
;    runtime, so it does not have to live in this file.\n\
;debug=no\n\
\n\
; downloaddir: this is the local directory where files are downloaded with the pscp integration\n\
;downloaddir=\n\
\n\
; uploaddir: default remote directory used by the pscp upload integration\n\
;uploaddir=.\n\
\n\
; fileextension: the extension for session settings files in portable mode\n\
;fileextension=.ktx\n\
\n\
; hyperlink: enable/disable the hyperlink feature\n\
;hyperlink=yes\n\
\n\
; iconfile: point to a file where internal icons are located\n\
;iconfile=kitty.exe\n\
\n\
; initdelay: initial delay in seconds before automatic sending of password, or auto command\n\
;initdelay=2.0\n\
\n\
; KiClassName: the Windows window-class name KiTTY registers, which also selects\n\
;    which registry hive it reads/writes sessions in. Default (unset): KiTTY's own\n\
;    class and hive (Software\\kapper.net\\KiTTY). Set to PuTTY to use stock PuTTY's\n\
;    window class AND PuTTY's hive (Software\\SimonTatham\\PuTTY) - handy to share\n\
;    sessions with an installed PuTTY, or for host tools that key off the \"PuTTY\"\n\
;    window class. This is NOT the default; leave it unset for normal use.\n\
;KiClassName=PuTTY\n\
\n\
; modalerrors: show connection errors as modal pop-up boxes instead of inline in the terminal (upstream cyd01/KiTTY #548). Default no (inline, non-trapping).\n\
;modalerrors=no\n\
\n\
; modalnewhostkeyconfirmation: how to confirm an UNKNOWN (first-seen) host key.\n\
;    Default yes = classic modal dialog box. no = OpenSSH-style prompt in the\n\
;    terminal; type \"yes\" to accept and cache the key, \"once\" to connect without\n\
;    caching it, anything else cancels.\n\
;modalnewhostkeyconfirmation=yes\n\
\n\
; modalchangedhostkeyconfirmation: how to handle a CHANGED host key (differs from\n\
;    the cached one). Default yes = classic modal dialog box (you can Accept to\n\
;    update the cache). no = in-terminal \"double opt-in\": first type \"yes\" to\n\
;    accept the new key for this connection, then - because KiTTY cannot verify a\n\
;    plain SSH key's authenticity - you are asked separately whether to REPLACE\n\
;    the stored key for future connections, which requires typing the exact word\n\
;    \"confirmed\" (a plain \"yes\" is re-asked, not accepted). Decline the replace\n\
;    and you connect this once with the old key kept (asked again next time).\n\
;modalchangedhostkeyconfirmation=yes\n\
\n\
; modalweakkeyconfirmation: how to confirm a weak crypto algorithm / weak cached\n\
;    host key (below the warning threshold). Default yes = classic modal dialog\n\
;    box. no = OpenSSH-style prompt in the terminal; type \"yes\" to accept.\n\
;    Note: all three of these prompts fall back to an in-terminal error + abort\n\
;    if they occur during an already-authenticated session (a rekey), where no\n\
;    inline prompt is possible.\n\
;modalweakkeyconfirmation=yes\n\
\n\
; mouseshortcuts: enable/disable mouse shortcuts\n\
;mouseshortcuts=yes\n\
\n\
; internaldelay: how long KiTTY pauses, in milliseconds, while it types for\n\
;    you - between the lines of a multi-line send, and around each\n\
;    synthesised keystroke that carries Ctrl/Shift/Alt. It paces the login\n\
;    and automatic commands, \\n breaks in the send-text boxes, user-command\n\
;    menu entries and remapped keys. Default 10, minimum 1.\n\
;    Raise it if a host drops characters out of a scripted or pasted block -\n\
;    a slow link or a shell that echoes lazily needs more than 10 ms per\n\
;    line. It has no effect on ordinary typing or on paste.\n\
;internaldelay=10\n\
\n\
; pastesize: warn before a large paste into the terminal. When the clipboard\n\
;    holds more than this many characters, KiTTY names the count and the\n\
;    limit and asks before sending anything - and the default answer is No,\n\
;    so a stray Enter cancels the paste instead of flooding the shell.\n\
;    The default is 5120 characters - about 5 KB, the same threshold Windows\n\
;    Terminal warns at. 0 switches the warning off entirely. It counts\n\
;    characters rather than lines, and judges only the size: what the\n\
;    clipboard actually contains is not examined.\n\
;    Note this key is read from the registry first (outside portable mode), so\n\
;    if a pastesize value ever lands there, changing the line here has no\n\
;    effect until you delete the registry value.\n\
;pastesize=5120\n\
\n\
; proxychainmax: how many chained SSH proxies (jump hosts) a connection may use\n\
;    before it is refused with an error. Stops a proxy chain that loops back on\n\
;    itself from hanging. Default 5; values below 1 are ignored.\n\
;proxychainmax=5\n\
\n\
; namedproxy: how a named proxy's Host field is read when the proxy entry\n\
;    itself does not say:\n\
;      sessionorhostname = the title of a saved session first, then a\n\
;                          hostname (the default - what PuTTY has always\n\
;                          done, and existing configurations may rely on it)\n\
;      hostname          = a hostname, full stop. Guards against a jump host\n\
;                          that happens to share a name with a saved session\n\
;                          silently dragging that session's whole config in.\n\
;    A proxy entry that says for itself overrides this.\n\
;namedproxy=sessionorhostname\n\
\n\
; funkeys: the default function-key mode for sessions that do not carry one,\n\
;    spelled as the Keyboard panel spells the modes: tilde, linux, xtermr6,\n\
;    vt400, vt100p, sco, xterm216. \"xterm216\" is the one worth setting - it\n\
;    is the only mode in which Shift+F1..F12 mean F13..F24 the way terminfo\n\
;    and every modern host expect.\n\
;funkeys=xterm216\n\
\n\
; verifyagent: a signed KiTTY checks, once per terminal window, whether the\n\
;    program answering its SSH agent requests is a verified KiTTY/kageant\n\
;    build, and warns when it is not. Set no if you deliberately run stock\n\
;    Pageant, the Windows OpenSSH agent or another agent. Also a checkbox:\n\
;    Connection -> SSH -> Auth (an application-wide setting, not per session).\n\
;verifyagent=yes\n\
\n\
; WorkplaceProxy / WorkplaceMinutes: the workplace-proxy-mode droplists'\n\
;    remembered LAST selection (which proxy, for how long), shared between\n\
;    the config box and the launcher menu so both offer the same thing next\n\
;    time. KiTTY writes these itself - not knobs to edit by hand, and NOT\n\
;    the mode's state: arming lives only in the running launcher.\n\
;WorkplaceProxy=\n\
;WorkplaceMinutes=240\n\
\n\
; PSCPPath: the full path to the file-copy helper - kscp.exe, or PuTTY's\n\
;    pscp.exe - used by drag-and-drop upload and the Send/Get file commands.\n\
;    You do not normally set this: KiTTY looks for the tool at startup and\n\
;    writes what it found back here. It searches, in order:\n\
;      1. this key, if it still points at a file that exists\n\
;      2. the pscpdir directory, kscp.exe first, then pscp.exe\n\
;      3. kscp.exe beside kitty.exe - the usual answer, since kscp ships\n\
;         with KiTTY and lives in the same folder\n\
;      4. %ProgramFiles%\\PuTTY\\pscp.exe\n\
;      5. pscp.exe beside kitty.exe\n\
;    A value naming a file that has gone away is dropped and the search runs\n\
;    again, so moving KiTTY does not leave it pointing at nothing. Set it by\n\
;    hand only to force a particular binary.\n\
;PSCPPath=\n\
\n\
; pscpdir: legacy fallback directory containing pscp.exe/kscp.exe (prefer PSCPPath)\n\
;pscpdir=\n\
\n\
; pscpport: the port kscp/pscp connects to for file transfer. Leave it unset\n\
;    and the transfer follows the SESSION's port - a host on 2222 transfers on\n\
;    2222, no second place to keep in step. * says the same thing explicitly.\n\
;    Give a number only to pin transfers to one port regardless of the session.\n\
;    (The old \"22\" shown here was wrong: unset has never meant 22.)\n\
;pscpport=*\n\
\n\
; ReconnectDelay: the delay before trying to reconnect automatically (in seconds)\n\
;ReconnectDelay=5\n\
\n\
; readonly: refuse to write to the CONFIGURATION FILE side of the settings.\n\
;    With yes, KiTTY will not write or delete entries in kitty.ini, will not\n\
;    create kitty.ini if it is missing, will not create the store's\n\
;    directories, and will not remove a legacy plaintext password it finds\n\
;    in the file. The configuration box says so instead of failing quietly.\n\
;    Not the same as conf=no, which is about KiTTY maintaining its OWN files\n\
;    (auto-creating kitty.ini, the kitty.sav and portable backups). readonly\n\
;    is the broader \"do not write\", and it covers deletes and directory\n\
;    creation as well.\n\
;    ⚠ Two things it does NOT do, despite the name: saved SESSIONS can still\n\
;    be written - they go through the session store, not this path - and in\n\
;    registry mode global settings are still written to the registry. Today\n\
;    it protects the ini file, not everything KiTTY stores.\n\
;readonly=no\n\
\n\
; restrictacl: apply the restricted process ACL to every KiTTY process, so you\n\
;    do not have to add -restrict-acl to each shortcut target. It denies other\n\
;    processes running as you the access rights used to read or write another\n\
;    process's memory - the same hardening as the -restrict-acl switch - and it\n\
;    propagates to the windows KiTTY spawns for you (config-box Start/Open,\n\
;    duplicate session, the launcher). kageant reads it too, so the process\n\
;    holding your loaded private keys is covered by the same setting.\n\
;    kittygen is not: pass it -restrict-acl if you want it hardened.\n\
;    Off by default, because it also blocks\n\
;    legitimate uses, notably screen readers and other accessibility tools.\n\
;    Worth knowing before an upgrade: an in-place MSI install will NOT reopen\n\
;    your sessions while this is on. Windows' Restart Manager cannot inspect\n\
;    a restricted process, so the installer closes those windows and cannot\n\
;    put them back. That is the hardening working as intended, not a fault in\n\
;    the installer - the whole point is that other processes running as you\n\
;    cannot reach into KiTTY, and the Restart Manager is one of them.\n\
;    yes is the only value that does anything: a process cannot un-restrict\n\
;    itself, so restrictacl=no does not lift a restriction already applied by\n\
;    -restrict-acl. If the ACL cannot be applied, KiTTY reports the error and\n\
;    exits rather than run unprotected.\n\
;    Unlike most keys here, this one is read from kitty.ini ONLY, never from\n\
;    the registry: the usual order consults the registry first, which would\n\
;    let a stale registry value silently cancel a restrictacl=yes written here.\n\
;restrictacl=no\n\
\n\
; sav: base path for the registry backup (a full export of KiTTY's hive). Each\n\
;    save writes a FRESH timestamped file next to it, <base>-YYYYMMDD-HHMMSS<ext>,\n\
;    so the filename always reflects when that copy was written. Default base is\n\
;    %APPDATA%\\KiTTY\\kittynew.sav (i.e. the files are kittynew-YYYYMMDD-HHMMSS.sav)\n\
;    - NOT kitty.sav, so an old 0.76 KiTTY's backup is never touched. A legacy\n\
;    value ending in kitty.sav or kitty084.sav is ignored so this default takes\n\
;    over; uncomment with a real path to force one.;    Backups left by earlier 0.84 builds (kitty-YYYYMMDD-HHMMSS.sav, from a\n\
;    defect that made the default kitty.sav after all) are still READ for a\n\
;    first-run restore; new ones are only ever written under the name above.\n\
;sav=\n\
\n\
; savbackupcount: in registry mode, how many timestamped backups to keep - the\n\
;    newest N are kept, older ones deleted. Default 5, max 50; 0 disables backups.\n\
;savbackupcount=5\n\
\n\
; savemode: specify the save mode for sessions settings\n\
;    Allowed values are:\n\
;    - registry : to save sessions into windows registry\n\
;    - file : to save sessions into one unique file (currently not maintained)\n\
;    - dir : to save sessions into files in the directory structure\n\
;savemode=registry\n\
\n\
; portablebackupcount: in portable dir mode, keep this many timestamped backups\n\
;    under Backups\\kitty-portable-YYYYMMDD-HHMMSS. 0 disables portable backups.\n\
;portablebackupcount=5\n\
\n\
; PortablePasswordProtection: at-rest protection for passwords saved in portable\n\
;    (savemode=dir) session files. Only applies in portable mode; in registry\n\
;    mode saved passwords are always protected with Windows DPAPI.\n\
;    Allowed values are:\n\
;    - master : protect saved passwords with a master password (default). Only\n\
;               the password fields are encrypted, the rest of the session file\n\
;               stays readable. Copy the files and know the master password to\n\
;               use them on another machine. KiTTY asks you to set the master\n\
;               password the first time it saves a password; -masterpwfile\n\
;               supplies it without a prompt.\n\
;    - dpapi  : protect saved passwords with Windows DPAPI, i.e. this Windows\n\
;               account on this PC. No master password is created and KiTTY\n\
;               never asks for one - so unattended runs need no switch at all -\n\
;               but the passwords do NOT travel: copied to another PC or account\n\
;               they cannot be decrypted. Cannot be combined with -masterpwfile.\n\
;    - legacy : store saved passwords unprotected (plain text) for explicit\n\
;               compatibility/automation/audit setups. INSECURE - anyone who can\n\
;               read the files gets the passwords.\n\
;PortablePasswordProtection=master\n\
\n\
; WarnLegacyPasswordUpgrade: in portable mode, warn before a save re-encrypts a\n\
;    password stored in the old unprotected format into the new protected format\n\
;    (old KiTTY releases cannot read the new format). Set to no to skip the\n\
;    warning and re-encrypt silently; the warning dialog can also set this.\n\
;WarnLegacyPasswordUpgrade=yes\n\
\n\
; scriptfilefilter: file-dialog filter for local script files.\n\
;    Default: (*.ksh,*.sh)|*.ksh;*.sh|SQL files (*.sql)|*.sql|All files (*.*)|*.*|\n\
;    The example line below narrows it to all files only:\n\
;scriptfilefilter=All files (*.*)|*.*|\n\
\n\
; scriptmode: master switch for the RuTTY script engine (send a script file\n\
;    line by line, with wait-for-prompt/halt-on patterns). no = disable the\n\
;    engine entirely: the session auto-script does not run and the\n\
;    \"Send a script file\" menu entry refuses with a notice.\n\
;scriptmode=yes\n\
\n\
; shortcuts: enable/disable KiTTY's keyboard shortcuts. These are the ones\n\
;    that work in a TERMINAL WINDOW - the [Shortcuts] section below binds\n\
;    them, and they are what the Ctrl+Shift+letter predefined commands ride\n\
;    on. Set no if they clash with a full-screen program inside the terminal\n\
;    (Midnight Commander is the usual example) and the key should reach the\n\
;    host instead.\n\
;    It does not affect the configuration box: Ctrl+F and Ctrl+G there are a\n\
;    separate mechanism and keep working either way. Nor does it affect the\n\
;    per-session global hotkey, which is registered with Windows.\n\
;shortcuts=yes\n\
\n\
; size: append the live terminal size, e.g. [24x80] (rows x columns), to the\n\
;    window title. Updates as you resize; hidden while maximized. Needs\n\
;    wintitle=yes (the default).\n\
;size=no\n\
\n\
; slidedelay: delay in seconds before automatic image switching in slideshow mode\n\
;    0 means no automatic slide, waiting for keyboard event\n\
;slidedelay=0\n\
\n\
; shrinkbitmap: shrink large background images to fit the terminal area\n\
;shrinkbitmap=no\n\
\n\
; sshversion: the client version string KiTTY announces to the SSH server.\n\
;    Default (unset): PuTTY-KiTTY - KiTTY's own identifier. Some servers reject a\n\
;    non-standard client-version string; set this to a common OpenSSH banner so\n\
;    KiTTY looks like a stock client. Use a current OpenSSH version, e.g.:\n\
;sshversion=OpenSSH_10.0\n\
\n\
; transparency: enable/disable the transparency feature\n\
;transparency=yes\n\
\n\
; userpasssshnosave: if yes, SSH password will not be saved internally (and can't be reused automatically)\n\
;userpasssshnosave=no\n\
\n\
; winroll: double-click the title bar to roll the window up into the title bar\n\
;   alone, and double-click again to restore it. Ctrl+F12 does the same (see\n\
;   [Shortcuts] rollup), as does the /winroll command.\n\
;winroll=yes\n\
\n\
; WinSCPPath: the full path to the winscp.exe binary:\n\
;WinSCPPath=\n\
\n\
; winscpdir: legacy fallback directory containing WinSCP.exe (prefer WinSCPPath)\n\
;winscpdir=\n\
\n\
; wintitle: enable KiTTY's window-title decorations: the live size suffix\n\
;    (size=yes) and the (PROTECTED) / (ONTOP) status markers. no = plain stock\n\
;    titles. Unlike classic KiTTY the title text is never parsed, only\n\
;    decorated - the old remote title-command channel stays removed.\n\
;wintitle=yes\n\
\n\
; zmodem: enable ZModem transfers (the sz/rz commands). The switch gates both\n\
;   the ZModem Receive/Upload/Abort entries in the terminal's Tools menu and\n\
;   the Connection > ZModem configuration panel: with it off, neither appears.\n\
;   On by default; set it to no to hide both.\n\
;zmodem=yes\n\
\n\
\n\
\n\
[Shortcuts]\n\
\n\
; list: the keys that have a user-defined action, separated by spaces. Each\n\
;    name listed here needs its own <key>=<text to send> line below, so\n\
;    \"list={F5} {CONTROL}{F6}\" expects a {F5}= and a {CONTROL}{F6}= line.\n\
;    Without the name in this list the key line is never read.\n\
;list={F5} {CONTROL}{F6}\n\
\n\
; Shortcuts: definition for the menu shortcuts keys\n\
\n\
; (re)send automatic command (default is SHIFT+F12)\n\
;autocommand=\n\
\n\
; Change settings ...\n\
;changesettings=\n\
\n\
; Clear scrollback\n\
;clearscrollback=\n\
\n\
; Clear log file\n\
;clearlogfile=\n\
\n\
; Close and restart current session\n\
;closerestart=\n\
\n\
; run a local command (default is CONTROL+F5)\n\
;command=\n\
\n\
; Copy all window buffers to clipboard\n\
;copyall=\n\
\n\
; Open a duplicate window (with same session settings)\n\
;duplicate=\n\
\n\
; open text editor connected to the main window (default is SHIFT+F2)\n\
;editor=\n\
\n\
; open text editor with clipboard content, connected to the main window (default is CONTROL+SHIFT+F2)\n\
;editorclipboard=\n\
\n\
; Show event log\n\
;eventlog=\n\
\n\
; Switch font to black on white colors\n\
;fontblackandwhite=\n\
\n\
; Decrease font size\n\
;fontdown=\n\
\n\
; Switch font to negative colors\n\
;fontnegative=\n\
\n\
; Increase font size\n\
;fontup=\n\
\n\
; Switch to full screen\n\
;fullscreen=\n\
\n\
; receive a remote file with pscp.exe: the full path must be selected in clipboard (default is CONTROL+F4)\n\
;getfile=\n\
\n\
; change the background image (default is CONTROL+F11)\n\
;imagechange=\n\
\n\
; special command box (default is CONTROL+F8)\n\
;input=\n\
\n\
; special command with multi-line editor (default is SHIFT+F8)\n\
;inputm=\n\
\n\
; Repeat key exchange\n\
;keyexchange=\n\
\n\
; New session ...\n\
;opennew=\n\
\n\
; Inherit New Session: a new configuration box carrying the current settings.\n\
;    In quick connect (see [ConfigBox] loadlastsession) the host name comes with\n\
;    them, selected and ready to be edited into the next machine; otherwise the\n\
;    box opens without a host.\n\
;opennewcurrent=\n\
\n\
; Print current clipboard content (default if SHIFT+F7)\n\
;print=\n\
\n\
; Print all window buffer content (default is F7)\n\
;printall=\n\
\n\
; Protect the window, disable keyboard and mouse input (default is CONTROL+F9)\n\
;protect=\n\
\n\
; Reset terminal\n\
;resetterminal=\n\
\n\
; Roll-up the window into the title bar (default is CONTROL+F12)\n\
;rollup=\n\
\n\
; Load a local script and run it remotely (default is CONTROL+F2)\n\
;script=\n\
\n\
; Send a local file with pscp.exe (default is CONTROL+F3)\n\
;sendfile=\n\
\n\
; Show current port forwarding definition (default is SHIFT+F6)\n\
;showportforward=\n\
\n\
; Enable or disable logging (default is SHIFT+F5)\n\
;switchlogmode=\n\
\n\
; Send the window to the system tray (default is CONTROL+F6)\n\
;tray=\n\
\n\
; Switch to embedded image viewer (default SHIFT+F11)\n\
;viewer=\n\
\n\
; Switch to always visible (default is CONTROL+F7)\n\
;visible=\n\
\n\
; Start WinSCP (default is SHIFT+F3)\n\
;winscp=\n\
\n\
\n\
\n\
[Print]\n\
\n\
; height: characters size (Printing)\n\
;height=100\n\
\n\
; maxline: maximum number of lines per page\n\
;maxline=60\n\
\n\
; maxchar: maximum number of characters per line\n\
;maxchar=85\n\
\n\
\n\
\n\
[Launcher]\n\
\n\
; alreadyRunCheck: what a second launcher does when one is already running.\n\
;    Unset (the default) the second one exits silently. yes = exit as well,\n\
;    stated explicitly. Any other value lets it start anyway, which is only\n\
;    useful when you deliberately want two launcher windows.\n\
;    One case ignores this setting entirely: a launcher started to HOLD\n\
;    workplace proxy mode. The launcher window class is shared by every\n\
;    KiTTY on the machine, while workplace mode is per installation - so a\n\
;    portable copy or a second install already in the tray owns that class,\n\
;    and a launcher started to arm OUR install would exit here without\n\
;    arming anything. Holding the arming therefore exempts it from the\n\
;    check. Two launchers of the SAME install still cannot both arm: the\n\
;    arming refuses a second holder, and that one exits like any duplicate.\n\
;alreadyRunCheck=yes\n\
\n\
; classname: override the Win32 window class the launcher registers and\n\
;    looks for. Only worth setting to keep two KiTTY installations from\n\
;    recognising each other as \"already running\".\n\
;classname=KiTTYLauncher\n\
\n\
; reload: enable session list reload on each menu respawn\n\
;reload=yes\n\
\n\
; exitwithworkplace: close the launcher again when workplace proxy mode is\n\
; switched off (default yes). Only applies to a launcher that the mode itself\n\
; started, by switching the mode on when none was running - a launcher you\n\
; started yourself always keeps running, because it is also your session list\n\
; and your hotkeys. Set no to keep the started one too.\n\
;exitwithworkplace=yes\n\
\n\
; noticeseconds: how long the workplace proxy mode notice stays on screen\n\
; (default 15). It is a window of our own rather than a tray balloon precisely\n\
; so that this is ours to set: Windows has ignored the requested balloon\n\
; duration since Vista, and a balloon cannot carry the mode's colour.\n\
;noticeseconds=15\n\
\n\
\n\
[Agent]\n\
\n\
; kageant (the SSH agent) settings. kageant finds this file on its own:\n\
; %KITTY_INI_FILE%, else kitty.ini/putty.ini next to kageant.exe, else\n\
; %APPDATA%\\KiTTY\\kitty.ini / %APPDATA%\\PuTTY\\putty.ini. When the file\n\
; says [KiTTY] savemode=file or savemode=dir, the ini is the authoritative\n\
; store: the tray toggles write back here and the registry is never touched\n\
; (portable mode). A portable folder counts even without the savemode\n\
; line: with savemode absent, a Sessions folder or KiTTYState file next\n\
; to the ini also makes it authoritative. Otherwise (savemode=registry,\n\
; or absent with no such layout) the registry stays authoritative and\n\
; these keys act as first-run defaults only.\n\
\n\
; askconfirmation: prompt before a loaded key may sign:\n\
;   yes  = every key use\n\
;   auto = only keys whose comment contains \"confirmation\" (default)\n\
;   no   = never - also disables the per-key comment prompts (automation)\n\
;askconfirmation=auto\n\
\n\
; messageonkeyusage: tray balloon naming the key after each signature\n\
; messageonkeyusage covers key USE (signatures) and, over IPC, key ADD /\n\
; REMOVE / REMOVE-ALL naming the requesting program - a notice, never a\n\
; prompt, so it does not break scripted ssh-add.\n\
;messageonkeyusage=yes\n\
\n\
; noticetimeout: how long the kageant notices stay on screen, in\n\
; seconds (2-120). One knob for all of them (key used, key added/\n\
; removed over IPC, startup keys missing). Absent = each notice's own\n\
; default. Hovering the pointer over a notice holds it open regardless.\n\
;noticetimeout=8\n\
\n\
; --- IPC access control (all default no). These restrict only requests\n\
; that arrive from OTHER programs over the agent protocol (WM_COPYDATA /\n\
; the named pipe, which is also what the Windows-OpenSSH integration\n\
; uses); the kageant window's own Add/Remove buttons are never affected.\n\
; Signing and listing keys are always allowed; re-encrypting a key is\n\
; allowed even under lockdown (it only tightens a key by dropping its\n\
; cleartext).\n\
; lockdownmode: refuse ALL key add/remove/remove-all over IPC.\n\
;lockdownmode=no\n\
; blockipcadd / blockipcremove: refuse just adds, or just removes.\n\
;blockipcadd=no\n\
;blockipcremove=no\n\
\n\
; loadkeysonstartup: re-add the remembered keys when kageant starts, added\n\
;    encrypted so the passphrase is asked on first use, not at login. Only the\n\
;    key FILE PATHS are remembered - never a passphrase or key material - and\n\
;    the list below is maintained for you as you add and remove keys.\n\
;    Off by default. Was called loadonstartup; the old name is read once and\n\
;    rewritten under this one.\n\
;    Note the tray item and the Settings checkbox are labelled \"Start kageant\n\
;    at login\": today that one command does both jobs - it installs the login\n\
;    autostart AND turns this on - and whether it looks ticked is decided by\n\
;    the autostart itself (the Run entry or Startup shortcut, checked to be\n\
;    THIS kageant), not by this setting.\n\
;loadkeysonstartup=no\n\
\n\
; startupkey1, startupkey2, ...: the remembered key files, in order. Paths\n\
; under this install folder are stored relative to it (so they travel); a\n\
; trailing \",encrypted\" loads that key deferred. kageant writes these when\n\
; you load keys with loadonstartup on - you normally do not edit them by hand.\n\
;startupkey1=keys\\id_ed25519.ppk,encrypted\n\
\n\
; --- Startup keys on removable media.\n\
; retrykeys: when a drive appears, load the startup keys that were not there\n\
; at login (they wait as \"not loaded\" rows in the key list rather than being\n\
; dropped). Default yes - it does nothing unless a startup key is actually\n\
; missing.\n\
;retrykeys=yes\n\
; unloadonremove: when the media a key came from goes away, drop that key\n\
; from the agent and put it back on the pending list, so it returns when the\n\
; media does. Default no, deliberately: pulling a stick must not break an\n\
; authentication that is running right now.\n\
;unloadonremove=no\n\
; quietmissingkeys: skip the startup notice that counts keys whose media is\n\
; absent (expected, when they live on a stick that is not always plugged\n\
; in). A key file that EXISTS but will not load is still reported - that is\n\
; a broken key, not an absent one.\n\
;quietmissingkeys=no\n\
\n\
; passphrasecacheseconds: how long a typed passphrase is kept (encrypted in\n\
; memory) to unlock further keys of a batch add without retyping it.\n\
; 0 = do not cache; capped at 300. Default 60.\n\
;passphrasecacheseconds=60\n\
\n\
; keylistgeometry / keylistcolumns: the key-list window's remembered\n\
; position/size and column widths. kageant writes these itself when the\n\
; window is moved, resized or closed - not knobs to edit by hand.\n\
;keylistgeometry=\n\
;keylistcolumns=\n\
\n\
\n\
[FontFallback]\n\
\n\
; Font fallback: when the terminal font is missing a character (box drawing,\n\
; Nerd Font icons, CJK, symbols...), KiTTY probes a list of fallback fonts\n\
; and draws that character from the first font that has it. Cell widths are\n\
; unchanged; only the glyph's source font differs. Rendering is plain GDI,\n\
; so emoji come out monochrome. NB: section and key names in this file are\n\
; case-sensitive.\n\
\n\
; active: master switch for the whole feature\n\
;active=yes\n\
\n\
; fallback: comma-separated list of font names to try, in order, before the\n\
; built-in defaults (Cascadia Mono, Cascadia Code, Segoe UI Symbol, Segoe UI\n\
; Emoji, Segoe UI Historic, Microsoft YaHei UI, Microsoft JhengHei UI,\n\
; Yu Gothic UI, Malgun Gothic). Naming a built-in just promotes it. Fonts\n\
; that are not installed are skipped. Start the list with ! to REPLACE the\n\
; built-in defaults instead.\n\
;fallback=Symbols Nerd Font Mono,JetBrains Mono\n\
;fallback=!MyOnlyFont1,MyOnlyFont2\n\
\n\
; override: force a Unicode range (or single codepoint, hex) to a specific\n\
; font regardless of probe results; multiple entries separated by ;\n\
;override=E000-F8FF:Symbols Nerd Font Mono;1F600-1F64F:Segoe UI Emoji\n\
\n\
; log: off|error|warn|info|debug|trace - troubleshooting log, written to\n\
; fontfallback.log next to kitty.exe (debug/trace are high volume)\n\
;log=off\n\
\n\
; logfile: where to write that log instead of the default. Unset, it goes to\n\
;    fontfallback.log in the folder the running executable sits in - which is\n\
;    read-only for a normal user under Program Files, so a per-user install or\n\
;    a portable copy gets the file and an installed one may not. Give a full\n\
;    path to put it somewhere writable, e.g. %USERPROFILE%\\fontfallback.log\n\
;    spelled out (this file does not expand environment variables).\n\
;    The file is appended to, and one previous copy is kept alongside it\n\
;    with a .1 suffix.\n\
;logfile=\n\
" ;
