#!/usr/bin/env python3
"""Generate kitty/kitty_ini.h - the kitty.ini KiTTY writes on first run - from
docs/examples/kitty.ini.example, the annotated reference.

There used to be two hand-maintained copies of the same template and they drifted:
the shipped one was 36 options behind the sample and had a key nothing read
(`winrol`). One source now feeds both, and every line is written commented out,
so a generated kitty.ini sets nothing and the compiled-in defaults stay in charge
- change a default in C and it reaches everyone who has not edited their file.

Re-run after editing the sample:  python3 tools/gen-kitty-ini-template.py
The drift check (tools/check-kitty-ini-example.py) fails the build if you forget.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "docs" / "examples" / "kitty.ini.example"
DST = ROOT / "kitty" / "kitty_ini.h"

# What the user sees at the top of the kitty.ini KiTTY creates for them. It is
# their file to edit - the "generated, do not edit" warning belongs on the
# header we compile, not on their copy.
BANNER = [
    "; kitty.ini - KiTTY's settings file. This one was created by KiTTY itself,",
    "; because there was none; it is yours to edit.",
    ";",
    "; Every supported option is listed below, commented out, led by a description.",
    "; Nothing here is in force: uncomment a line to use it. The values shown are",
    "; the built-in defaults, so uncommenting a line unchanged does nothing today -",
    "; but it does pin that value, where a commented line keeps following the",
    "; default if a later KiTTY changes it.",
    ";",
    "; Some settings are also held in the registry, and outside portable mode the",
    "; registry is read first - so if an edit here seems to have no effect, that is",
    "; usually why. See",
    ";   https://github.com/hknet/KiTTY/blob/kitty-0.84/docs/KITTY-INI.md",
    "",
]


def c_escape(line: str) -> str:
    return line.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    src = SRC.read_text(encoding="utf-8").splitlines()

    # The sample opens with its own "this file is inert, copy it to kitty.ini"
    # header, which makes no sense in the file KiTTY just created for you - and
    # reads as a second banner under ours. Start at the first [Section].
    first = next(i for i, l in enumerate(src) if l.lstrip().startswith("["))
    src = src[first:]

    out = []
    for line in BANNER + src:
        s = line.rstrip()
        # every key line is written commented out - the file must set nothing
        if s and not s.lstrip().startswith(";") and not s.lstrip().startswith("["):
            s = ";" + s.lstrip()
        out.append(s)

    # trim a trailing run of blank lines to exactly one
    while len(out) > 1 and out[-1] == "" and out[-2] == "":
        out.pop()

    body = "".join(f"{c_escape(l)}\\n\\\n" for l in out)
    DST.write_text(
        "/* Generated by tools/gen-kitty-ini-template.py from\n"
        " * docs/examples/kitty.ini.example - do not edit by hand. This is the\n"
        " * kitty.ini KiTTY writes when it starts and finds none. */\n"
        f'char default_init_file_content[] = "{body}" ;\n',
        encoding="utf-8", newline="\n")

    keys = sum(1 for l in out if l.startswith(";") and "=" in l.split(";", 1)[1][:60]
               and not l.startswith("; "))
    print(f"wrote {DST.relative_to(ROOT)}: {len(out)} lines, ~{keys} option lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
